import img from "@/assets/curriculum/ai-engineering.jpg";
import type { CourseCurriculum } from "./types";

// ---------- AI ENGINEERING (AI Track 3 of 3) ----------
export const aiEngineering: CourseCurriculum = {
  slug: "ai-engineering",
  title: "AI Engineering",
  tagline: "AI Track (3 of 3)",
  duration: "2 Months (8 Weeks)",
  months: 2,
  totalWeeks: 8,
  level: "Intermediate to Industry Ready",
  projectsCount: "10+",
  capstone: "1 Production AI Application",
  goal: "Train engineers to design, build, evaluate, secure, and ship production-grade AI applications powered by large language models, retrieval systems, and autonomous agents.",
  overview:
    "An intensive, project-driven program covering the full AI engineering stack: Python fundamentals for AI, LLM internals, prompt and structured output engineering, retrieval-augmented generation, agentic systems with tool use, fine-tuning, multimodal AI, and production deployment with observability and security. Students ship a capstone production AI application backed by FastAPI, a vector database, and an evaluation pipeline.",
  image: img,
  weeks: [
    {
      number: 1,
      title: "Python for AI & LLM Foundations",
      overview:
        "Refresh Python for AI workloads and build a rigorous mental model of how large language models actually work under the hood.",
      objectives: [
        "Write production-quality Python for AI applications",
        "Explain tokenization, embeddings, and transformer architecture in depth",
        "Understand context windows and their practical limits",
        "Call multiple LLM provider APIs correctly and idiomatically",
      ],
      sections: [
        {
          id: "1.1",
          title: "Python Refresher for AI Engineers",
          topics: [
            "Virtual environments with venv and uv",
            "Type hints and Pydantic models",
            "Async/await and asyncio basics",
            "Working with JSON and dataclasses",
            "HTTP requests with httpx",
            "Error handling and retries with tenacity",
            "Environment variable management with python-dotenv",
            "Logging with the logging module",
            "List/dict comprehensions for data wrangling",
            "Generators and streaming iterators",
            "Working with .env secrets safely",
            "Package management with pip and pyproject.toml",
          ],
        },
        {
          id: "1.2",
          title: "How LLMs Actually Work",
          topics: [
            "What is a large language model",
            "Tokenization (BPE, SentencePiece)",
            "Vocabulary size and token limits",
            "Embeddings and vector representations",
            "Self-attention mechanism explained",
            "Transformer architecture (encoder/decoder)",
            "Positional encoding",
            "Next-token prediction as the core objective",
            "Temperature, top-p, top-k sampling",
            "Context window and its impact on cost/latency",
            "Pretraining vs fine-tuning vs RLHF",
            "Model families: GPT, Claude, Gemini, Llama, Mistral",
            "Open-source vs closed-source models",
            "Model cards and benchmarks (MMLU, HumanEval)",
          ],
        },
        {
          id: "1.3",
          title: "Working with LLM Provider APIs",
          topics: [
            "OpenAI API (chat completions, responses API)",
            "Anthropic Claude API (messages API)",
            "Google Gemini API",
            "Open-source models via Ollama and Hugging Face",
            "API keys and authentication",
            "Rate limits and quota management",
            "System, user, and assistant roles",
            "Multi-turn conversation state management",
            "Comparing pricing across providers",
            "Choosing the right model for a task",
            "Local vs hosted model tradeoffs",
          ],
        },
        {
          id: "1.4",
          title: "Prompt Engineering Fundamentals",
          topics: [
            "Zero-shot vs few-shot prompting",
            "Chain-of-thought prompting",
            "System prompt design patterns",
            "Role-based prompting",
            "Delimiters and structured prompt templates",
            "Prompt injection risks (introductory)",
            "Iterative prompt refinement workflow",
            "Prompt versioning and testing",
          ],
        },
      ],
      exercises: [
        "Build a CLI chatbot using the OpenAI API with conversation memory",
        "Tokenize sample text with tiktoken and visualize token counts",
        "Compare responses from three different providers for the same prompt",
        "Implement exponential backoff retry logic for rate-limited API calls",
      ],
      assignments: [
        "Write a technical explainer document on transformer self-attention with diagrams",
        "Build a Python script that benchmarks latency and cost across GPT, Claude, and Gemini",
      ],
      projects: [
        "Multi-provider LLM playground CLI with model switching and cost tracking",
      ],
      outcomes: [
        "Can explain LLM internals confidently in a technical interview",
        "Can call and switch between major LLM provider APIs",
        "Understands token economics and context window tradeoffs",
        "Writes clean async Python for AI workloads",
      ],
      assessment: "Timed quiz on transformer internals plus a working multi-provider chatbot CLI submission",
    },
    {
      number: 2,
      title: "Structured Outputs, Function Calling & Tool Use",
      overview:
        "Move beyond free-text generation into reliable, machine-readable outputs and model-invoked tool calls.",
      objectives: [
        "Force LLMs to return valid structured JSON reliably",
        "Design and implement function/tool calling schemas",
        "Validate and repair malformed LLM outputs",
        "Build a basic tool-using assistant",
      ],
      sections: [
        {
          id: "2.1",
          title: "Structured Output Generation",
          topics: [
            "JSON mode in OpenAI and Anthropic APIs",
            "Pydantic schemas for output validation",
            "Instructor library for typed LLM outputs",
            "JSON schema design best practices",
            "Handling malformed JSON gracefully",
            "Retry-with-repair strategies",
            "Enum constraints and structured classification",
            "Nested object extraction from unstructured text",
          ],
        },
        {
          id: "2.2",
          title: "Function Calling & Tool Definitions",
          topics: [
            "Function calling API in OpenAI",
            "Tool use in Anthropic Claude",
            "Designing clear tool descriptions and parameters",
            "Multi-tool selection logic",
            "Parallel function calling",
            "Handling tool call errors and fallbacks",
            "Chaining multiple tool calls in one turn",
            "Security considerations for tool execution",
          ],
        },
        {
          id: "2.3",
          title: "Building Practical Tools",
          topics: [
            "Weather API tool integration",
            "Database query tool with parameterized SQL",
            "Web search tool integration",
            "Calculator and code execution tools",
            "File read/write tools with sandboxing",
            "Designing a tool registry pattern",
          ],
        },
        {
          id: "2.4",
          title: "Output Validation & Reliability",
          topics: [
            "Schema validation with Pydantic v2",
            "Guardrails-style output checking",
            "Confidence scoring heuristics",
            "Handling hallucinated fields",
            "Logging and replaying failed generations",
          ],
        },
      ],
      exercises: [
        "Extract structured invoice data from unstructured text into a Pydantic model",
        "Build a function-calling weather assistant with a mock API",
        "Implement a JSON repair loop for malformed model outputs",
        "Chain three tool calls together to answer a compound question",
      ],
      assignments: [
        "Build a structured data extraction pipeline for resumes into a typed schema",
        "Design and document a tool registry supporting 5 distinct tools",
      ],
      projects: [
        "Tool-using research assistant that can search, calculate, and summarize with structured output",
      ],
      outcomes: [
        "Reliably extracts typed structured data from LLMs",
        "Designs safe, well-documented tool schemas",
        "Builds assistants that can call external functions",
        "Handles malformed model output gracefully in production",
      ],
      assessment: "Code review of a tool-calling assistant with structured output validation",
    },
    {
      number: 3,
      title: "Retrieval-Augmented Generation (RAG) I",
      overview:
        "Ground LLMs in external knowledge using embeddings, chunking strategies, and vector search.",
      objectives: [
        "Understand and implement document chunking strategies",
        "Generate and store embeddings in vector databases",
        "Build a basic RAG pipeline end-to-end",
        "Evaluate retrieval quality",
      ],
      sections: [
        {
          id: "3.1",
          title: "RAG Fundamentals",
          topics: [
            "Why RAG: hallucination and knowledge cutoff problems",
            "RAG architecture overview (ingest, retrieve, generate)",
            "Naive RAG vs advanced RAG pipelines",
            "When to use RAG vs fine-tuning vs long context",
            "RAG evaluation metrics overview",
          ],
        },
        {
          id: "3.2",
          title: "Document Processing & Chunking",
          topics: [
            "Loading PDFs, HTML, Markdown, and DOCX",
            "Fixed-size chunking",
            "Recursive character text splitting",
            "Semantic chunking strategies",
            "Chunk overlap tuning",
            "Metadata tagging per chunk",
            "Handling tables and images in documents",
            "Chunking tradeoffs for retrieval quality",
          ],
        },
        {
          id: "3.3",
          title: "Embeddings",
          topics: [
            "OpenAI text-embedding models",
            "Open-source embedding models (BGE, E5, sentence-transformers)",
            "Embedding dimensionality and cost tradeoffs",
            "Batch embedding generation",
            "Cosine similarity and vector distance metrics",
            "Embedding normalization",
            "Domain-specific embedding fine-tuning (overview)",
          ],
        },
        {
          id: "3.4",
          title: "Vector Databases",
          topics: [
            "pgvector on PostgreSQL setup and indexing",
            "Pinecone setup and namespaces",
            "Qdrant setup and collections",
            "HNSW and IVF indexing concepts",
            "Metadata filtering in vector search",
            "Hybrid search (keyword + vector)",
            "Choosing a vector DB for a given use case",
            "Scaling vector search for millions of vectors",
          ],
        },
      ],
      exercises: [
        "Chunk a 100-page PDF using three different chunking strategies and compare results",
        "Generate embeddings for a document set and store them in pgvector",
        "Build a hybrid search query combining keyword and vector similarity in Qdrant",
        "Benchmark retrieval latency across pgvector, Pinecone, and Qdrant",
      ],
      assignments: [
        "Build an end-to-end ingestion pipeline: load, chunk, embed, and store documents",
        "Write a report comparing three vector databases on cost, latency, and features",
      ],
      projects: [
        "Document Q&A system over a custom PDF knowledge base using pgvector",
      ],
      outcomes: [
        "Designs effective chunking strategies for different document types",
        "Confidently sets up and queries pgvector, Pinecone, and Qdrant",
        "Understands embedding model tradeoffs",
        "Builds a working ingestion-to-retrieval pipeline",
      ],
      assessment: "Working RAG ingestion pipeline demo with retrieval quality walkthrough",
    },
    {
      number: 4,
      title: "RAG II: Advanced Retrieval, Evaluation & Guardrails",
      overview:
        "Push RAG systems to production quality with advanced retrieval techniques, rigorous evaluation, and safety guardrails.",
      objectives: [
        "Implement advanced retrieval techniques to reduce hallucination",
        "Build automated RAG evaluation pipelines",
        "Apply guardrails against unsafe or off-topic outputs",
        "Optimize a RAG system for accuracy and latency",
      ],
      sections: [
        {
          id: "4.1",
          title: "Advanced Retrieval Techniques",
          topics: [
            "Query rewriting and expansion",
            "HyDE (Hypothetical Document Embeddings)",
            "Multi-query retrieval",
            "Re-ranking with cross-encoders",
            "Maximal marginal relevance (MMR)",
            "Parent-document and small-to-big retrieval",
            "Contextual compression",
            "Self-querying retrievers with metadata filters",
          ],
        },
        {
          id: "4.2",
          title: "RAG Evaluation",
          topics: [
            "Retrieval metrics: precision@k, recall@k, MRR",
            "Generation metrics: faithfulness, relevance, groundedness",
            "RAGAS evaluation framework",
            "Building golden datasets for evaluation",
            "LLM-as-judge evaluation patterns",
            "Regression testing for RAG pipelines",
            "A/B testing retrieval strategies",
          ],
        },
        {
          id: "4.3",
          title: "Guardrails & Safety",
          topics: [
            "Input validation and content filtering",
            "Output moderation APIs (OpenAI moderation, Guardrails AI)",
            "Topical guardrails (staying on-topic)",
            "PII detection and redaction",
            "Hallucination detection heuristics",
            "Refusal handling and fallback responses",
            "Rate limiting abusive queries",
          ],
        },
        {
          id: "4.4",
          title: "Production RAG Patterns",
          topics: [
            "Citation and source attribution in responses",
            "Streaming RAG responses to the client",
            "Caching retrieval results",
            "Incremental document re-indexing",
            "Multi-tenant RAG data isolation",
            "Handling conflicting or outdated sources",
          ],
        },
      ],
      exercises: [
        "Implement query rewriting to improve retrieval on ambiguous questions",
        "Build a RAGAS evaluation harness against a golden Q&A dataset",
        "Add PII redaction to an ingestion pipeline",
        "Implement citation attribution in a RAG chatbot's responses",
      ],
      assignments: [
        "Build a full evaluation pipeline scoring faithfulness and relevance on 50 test questions",
        "Write a guardrails policy document and implement it in code",
      ],
      projects: [
        "Production-grade support-docs chatbot with re-ranking, citations, and guardrails",
      ],
      outcomes: [
        "Builds RAG systems resistant to hallucination",
        "Runs automated, repeatable RAG evaluation pipelines",
        "Implements practical safety guardrails",
        "Ships RAG features with source citations",
      ],
      assessment: "Present a RAGAS evaluation report with before/after metrics from applied improvements",
    },
    {
      number: 5,
      title: "Agents & Tool-Using Systems",
      overview:
        "Build autonomous, multi-step AI agents that plan, use tools, and collaborate using LangChain, LangGraph, and MCP.",
      objectives: [
        "Understand agent architectures and reasoning loops",
        "Build stateful agents with LangGraph",
        "Integrate the Model Context Protocol (MCP) for tool interoperability",
        "Design multi-agent collaboration workflows",
      ],
      sections: [
        {
          id: "5.1",
          title: "Agent Fundamentals",
          topics: [
            "ReAct pattern (reason + act)",
            "Plan-and-execute agents",
            "Agent memory: short-term vs long-term",
            "Tool selection and routing logic",
            "Agent loops and termination conditions",
            "Failure modes: infinite loops, tool misuse",
            "Cost and latency implications of agentic loops",
          ],
        },
        {
          id: "5.2",
          title: "LangChain Framework",
          topics: [
            "LangChain core abstractions (chains, runnables)",
            "LCEL (LangChain Expression Language)",
            "Prompt templates and output parsers",
            "Memory modules in LangChain",
            "Retrievers and vector store integrations",
            "Callbacks and tracing hooks",
            "LangChain agents and toolkits",
          ],
        },
        {
          id: "5.3",
          title: "LangGraph for Stateful Agents",
          topics: [
            "Graph-based agent orchestration",
            "Nodes, edges, and state schemas",
            "Conditional branching in agent graphs",
            "Human-in-the-loop checkpoints",
            "Persistent state and checkpointing",
            "Cyclic graphs for iterative reasoning",
            "Multi-agent supervisor patterns",
          ],
        },
        {
          id: "5.4",
          title: "Model Context Protocol (MCP)",
          topics: [
            "What MCP is and why it matters",
            "MCP servers and clients architecture",
            "Exposing tools via an MCP server",
            "Connecting Claude/other clients to MCP servers",
            "Resource and prompt primitives in MCP",
            "Building a custom MCP server for internal tools",
          ],
        },
        {
          id: "5.5",
          title: "Multi-Agent Systems",
          topics: [
            "Supervisor-worker agent patterns",
            "Agent-to-agent communication protocols",
            "Task decomposition across agents",
            "Shared state and blackboard patterns",
            "Debugging multi-agent failures",
          ],
        },
      ],
      exercises: [
        "Build a ReAct agent that solves multi-step math and lookup tasks",
        "Implement a LangGraph workflow with a human-approval checkpoint",
        "Build a minimal MCP server exposing a file-search tool",
        "Design a two-agent supervisor-worker pipeline for report generation",
      ],
      assignments: [
        "Build a LangGraph customer support agent with escalation logic",
        "Write an MCP server exposing at least three tools with proper schemas",
      ],
      projects: [
        "Autonomous research agent that plans, searches, retrieves, and synthesizes a report",
      ],
      outcomes: [
        "Designs and debugs multi-step agent reasoning loops",
        "Builds production agents with LangGraph state management",
        "Exposes and consumes tools via MCP",
        "Orchestrates multi-agent collaborative workflows",
      ],
      assessment: "Live demo of an autonomous multi-tool agent solving an open-ended research task",
    },
    {
      number: 6,
      title: "Fine-Tuning, Multimodal AI & Model Customization",
      overview:
        "Customize models via fine-tuning and LoRA, and extend AI applications across vision, speech, and image generation.",
      objectives: [
        "Fine-tune LLMs using LoRA and parameter-efficient methods",
        "Prepare high-quality fine-tuning datasets",
        "Build multimodal applications using vision, speech, and image models",
        "Choose between prompting, RAG, and fine-tuning appropriately",
      ],
      sections: [
        {
          id: "6.1",
          title: "Fine-Tuning Fundamentals",
          topics: [
            "When to fine-tune vs prompt vs RAG",
            "Full fine-tuning vs parameter-efficient fine-tuning",
            "LoRA and QLoRA explained",
            "Dataset formatting for fine-tuning (JSONL)",
            "Fine-tuning via OpenAI's fine-tuning API",
            "Fine-tuning open-source models with Hugging Face PEFT",
            "Evaluation before/after fine-tuning",
            "Overfitting and catastrophic forgetting risks",
          ],
        },
        {
          id: "6.2",
          title: "Dataset Preparation",
          topics: [
            "Collecting and cleaning training examples",
            "Synthetic data generation with LLMs",
            "Data deduplication and quality filtering",
            "Train/validation split strategy",
            "Labeling and annotation workflows",
            "Bias detection in training data",
          ],
        },
        {
          id: "6.3",
          title: "Vision & Multimodal Models",
          topics: [
            "Vision-language models (GPT-4o vision, Gemini vision, Claude vision)",
            "Image understanding and OCR use cases",
            "Image generation APIs (DALL-E, Imagen, Stable Diffusion)",
            "Prompt engineering for image generation",
            "Document and chart understanding with vision models",
            "Building a visual question-answering feature",
          ],
        },
        {
          id: "6.4",
          title: "Speech & Audio AI",
          topics: [
            "Speech-to-text with Whisper API",
            "Text-to-speech APIs (OpenAI TTS, ElevenLabs)",
            "Real-time voice pipelines",
            "Building a voice assistant end-to-end",
            "Audio streaming considerations",
          ],
        },
      ],
      exercises: [
        "Prepare a JSONL fine-tuning dataset from support ticket transcripts",
        "Fine-tune an open-source model with LoRA using Hugging Face PEFT",
        "Build a vision feature that extracts data from receipts using GPT-4o vision",
        "Build a voice memo transcription and summarization pipeline with Whisper",
      ],
      assignments: [
        "Fine-tune a model on a custom style/task and document before/after evaluation results",
        "Build a multimodal feature combining vision input and structured output",
      ],
      projects: [
        "Voice-enabled multimodal assistant: speech in, vision analysis, speech out",
      ],
      outcomes: [
        "Fine-tunes models using LoRA/QLoRA appropriately",
        "Prepares clean, well-structured fine-tuning datasets",
        "Builds vision and speech-enabled AI features",
        "Makes informed prompting vs RAG vs fine-tuning decisions",
      ],
      assessment: "Present a fine-tuning experiment report with quantitative before/after comparisons",
    },
    {
      number: 7,
      title: "Production AI Backends: Performance, Observability & Security",
      overview:
        "Engineer AI backends for real-world scale: FastAPI services, cost/latency optimization, observability, and security hardening against prompt injection.",
      objectives: [
        "Build production FastAPI backends serving AI features",
        "Optimize AI applications for cost and latency",
        "Instrument AI pipelines with observability tooling",
        "Defend applications against prompt injection and abuse",
      ],
      sections: [
        {
          id: "7.1",
          title: "FastAPI for AI Backends",
          topics: [
            "FastAPI project structure for AI services",
            "Async endpoints for LLM calls",
            "Server-sent events and streaming responses",
            "WebSocket support for real-time chat",
            "Request/response schemas with Pydantic",
            "Background tasks for long-running AI jobs",
            "API authentication and rate limiting",
            "Dependency injection for shared AI clients",
          ],
        },
        {
          id: "7.2",
          title: "Cost & Latency Optimization",
          topics: [
            "Token usage tracking and budgeting",
            "Prompt compression techniques",
            "Choosing smaller models for simple tasks (model routing)",
            "Response caching strategies (semantic caching)",
            "Batch processing for non-realtime workloads",
            "Streaming to reduce perceived latency",
            "Parallelizing independent LLM calls",
            "Cost monitoring dashboards",
          ],
        },
        {
          id: "7.3",
          title: "Observability with LangSmith",
          topics: [
            "Tracing LLM calls end-to-end",
            "Debugging chains and agent runs visually",
            "Logging prompts, completions, and metadata",
            "Dataset creation from production traces",
            "Automated evaluation runs in LangSmith",
            "Alerting on latency and error spikes",
            "A/B testing prompts in production",
          ],
        },
        {
          id: "7.4",
          title: "Security & Prompt Injection Defense",
          topics: [
            "Direct vs indirect prompt injection",
            "Jailbreak attempts and mitigation strategies",
            "Sandboxing tool execution",
            "Input/output sanitization",
            "Least-privilege tool permissions",
            "Data exfiltration risks via RAG documents",
            "Red-teaming your own AI application",
            "Secrets management for API keys",
          ],
        },
        {
          id: "7.5",
          title: "Deployment & MLOps",
          topics: [
            "Containerizing AI services with Docker",
            "Deploying FastAPI AI backends (Railway, Fly.io, AWS)",
            "CI/CD for AI applications",
            "Environment-based configuration (dev/staging/prod)",
            "Model version pinning and rollback strategy",
            "Load testing AI endpoints",
            "Monitoring uptime and error rates in production",
          ],
        },
      ],
      exercises: [
        "Build a streaming FastAPI chat endpoint with SSE",
        "Implement semantic caching to reduce duplicate LLM calls",
        "Instrument a LangChain pipeline with LangSmith tracing",
        "Attempt a prompt injection attack on your own RAG app and patch it",
      ],
      assignments: [
        "Deploy a FastAPI AI backend to a cloud provider with CI/CD",
        "Write a security assessment report covering prompt injection defenses implemented",
      ],
      projects: [
        "Production-ready AI backend with streaming, caching, tracing, and deployed CI/CD pipeline",
      ],
      outcomes: [
        "Ships FastAPI backends serving real AI features at scale",
        "Reduces cost and latency through concrete optimization techniques",
        "Uses LangSmith for full pipeline observability",
        "Hardens AI applications against common security threats",
      ],
      assessment: "Deployed AI backend review including load test results and security checklist",
    },
    {
      number: 8,
      title: "Capstone: Production AI Application",
      overview:
        "Design, build, evaluate, secure, and deploy a complete production AI application integrating everything learned in the track.",
      objectives: [
        "Architect a complete production AI system from scratch",
        "Integrate RAG, agents, and structured outputs into one cohesive product",
        "Apply evaluation, guardrails, and observability throughout",
        "Deploy and present a polished, working AI application",
      ],
      sections: [
        {
          id: "8.1",
          title: "Capstone Planning & Architecture",
          topics: [
            "Choosing a capstone problem with real user value",
            "System architecture diagramming",
            "Data source identification and licensing",
            "Tech stack selection (FastAPI, vector DB, frontend)",
            "Scoping MVP vs stretch features",
            "Defining success metrics upfront",
          ],
        },
        {
          id: "8.2",
          title: "Core Build Sprint",
          topics: [
            "Ingestion and RAG pipeline implementation",
            "Agent/tool integration for multi-step tasks",
            "Structured output contracts for the frontend",
            "Streaming chat interface implementation",
            "Authentication and multi-user data isolation",
            "Persisting conversation and document history",
          ],
        },
        {
          id: "8.3",
          title: "Evaluation, Guardrails & Hardening",
          topics: [
            "Building a golden evaluation dataset for the capstone domain",
            "Running RAGAS or custom evaluation suite",
            "Adding moderation and prompt injection defenses",
            "Cost and latency profiling under load",
            "Fixing top failure cases found during testing",
          ],
        },
        {
          id: "8.4",
          title: "Deployment, Observability & Launch",
          topics: [
            "Dockerizing and deploying the full stack",
            "Setting up LangSmith tracing in production",
            "Configuring monitoring and alerting",
            "Writing technical documentation and architecture diagrams",
            "Preparing a live demo and pitch deck",
            "Portfolio presentation and code walkthrough",
          ],
        },
      ],
      exercises: [
        "Write an architecture decision record (ADR) for the capstone tech stack",
        "Run a full evaluation suite and document results before final polish",
        "Conduct a peer red-team session against your deployed capstone",
      ],
      assignments: [
        "Submit a complete capstone architecture document with diagrams",
        "Submit final evaluation report with metrics and remediation notes",
      ],
      projects: [
        "Capstone: fully deployed production AI application with RAG, agents, evaluation, and observability",
      ],
      outcomes: [
        "Ships a complete, deployed, production-grade AI application solo",
        "Demonstrates mastery of RAG, agents, evaluation, and security",
        "Presents technical work clearly to both technical and non-technical audiences",
        "Has a portfolio-ready capstone project for job applications",
      ],
      assessment: "Live capstone demo and defense in front of instructors and peers, graded on architecture, functionality, evaluation rigor, and presentation",
    },
  ],
};
