import type { CourseCurriculum } from "./types";
import img from "@/assets/curriculum/data-analytics.jpg";

export const dataAnalytics: CourseCurriculum = {
  slug: "data-analytics",
  title: "Data Analytics",
  tagline: "Professional Diploma",
  duration: "4 Months (16 Weeks)",
  months: 4,
  totalWeeks: 16,
  level: "Beginner → Intermediate → Advanced → Industry Ready",
  projectsCount: "15+",
  capstone: "1 End-to-End Analytics Product with Dashboard",
  goal: "Train students to become professional data analysts who can source, clean, model, analyze, and visualize data, and confidently turn raw numbers into business decisions using Excel, SQL, Python, statistics, BI tools, and light machine learning — finishing job-ready with a portfolio of real-world projects and a deployed capstone analytics product.",
  overview: "A rigorous 16-week professional diploma covering the full analytics stack: spreadsheet mastery, SQL querying and data modeling, Python and Pandas for data wrangling, exploratory data analysis and statistics, business intelligence tools (Power BI, Tableau, Looker Studio), data storytelling, data warehousing and pipelines, product analytics, and an introduction to machine learning for analysts. Every week combines hands-on exercises with real, messy datasets so students build a portfolio of 15+ projects, culminating in a deployed end-to-end analytics product with an interactive dashboard and executive report.",
  image: img,
  weeks: [
    {
      number: 1,
      title: "Data Analytics Foundations",
      overview: "Orient students to the analytics profession, the data lifecycle, and the tools they will use for the next 16 weeks, while building a shared vocabulary for thinking about data-driven decisions.",
      objectives: [
        "Distinguish the roles of data analyst, data scientist, and data engineer",
        "Describe the end-to-end data lifecycle from collection to decision",
        "Apply the descriptive, diagnostic, predictive, and prescriptive analytics framework",
        "Set up a professional analytics toolkit (Excel, SQL client, Python, Git, BI tool)",
        "Read and interpret a basic business dashboard",
      ],
      sections: [
        {
          id: "1.1",
          title: "The Data Landscape",
          topics: [
            "Analyst vs Data Scientist vs Data Engineer vs BI Developer role breakdown",
            "The data lifecycle: collect, store, clean, analyze, visualize, act",
            "Structured, semi-structured, and unstructured data types",
            "Common data sources: databases, APIs, spreadsheets, logs, third-party feeds",
            "Industries that hire analysts: fintech, e-commerce, healthcare, SaaS, retail",
            "Data governance, privacy, and ethics basics (GDPR, data anonymization)",
            "A day in the life of a working data analyst",
            "Career paths and salary benchmarks in analytics",
          ],
        },
        {
          id: "1.2",
          title: "Data Thinking",
          topics: [
            "Descriptive vs diagnostic vs predictive vs prescriptive analytics",
            "Metrics vs dimensions vs attributes",
            "KPIs, North Star metrics, and vanity metrics",
            "Formulating a good analytical question (from vague ask to measurable question)",
            "Hypothesis-driven analysis vs exploratory analysis",
            "Correlation vs causation pitfalls",
            "Data quality dimensions: accuracy, completeness, consistency, timeliness",
          ],
        },
        {
          id: "1.3",
          title: "Tooling Overview",
          topics: [
            "Excel and Google Sheets for lightweight analysis",
            "SQL and relational databases (PostgreSQL, MySQL) for querying at scale",
            "Python, Jupyter Notebook, and Google Colab for scripted analysis",
            "BI tools: Power BI, Tableau, and Looker Studio for dashboards",
            "Git and GitHub for version control of notebooks and scripts",
            "Setting up a local Python environment with Anaconda/venv and VS Code",
            "Connecting tools together: exporting from SQL to Python to BI",
          ],
        },
      ],
      exercises: [
        "Map out the data lifecycle for a real company (e.g., a food delivery app)",
        "Classify 10 sample datasets as structured, semi-structured, or unstructured",
        "Write 5 well-formed analytical questions from a vague business ask",
        "Install and configure Python, Jupyter, a SQL client, and a BI tool",
      ],
      assignments: [
        "Submit a one-page personal analytics toolkit setup with screenshots",
        "Write a short brief on which analytics role you are aiming for and why",
      ],
      projects: [
        "Analytics Toolkit Setup & Personal Learning Roadmap document",
      ],
      outcomes: [
        "Understands the analytics profession and data lifecycle",
        "Can frame vague business asks as measurable analytical questions",
        "Has a fully configured analytics toolkit (Excel, SQL, Python, BI, Git)",
        "Can distinguish descriptive, diagnostic, predictive, and prescriptive work",
      ],
      assessment: "Graded toolkit setup and question-framing exercise reviewed for completeness and clarity",
    },
    {
      number: 2,
      title: "Excel & Google Sheets Mastery",
      overview: "Build deep fluency in spreadsheets as the fastest tool for everyday business analysis, from core formulas to pivot tables and dashboards.",
      objectives: [
        "Write advanced lookup, conditional, and text formulas confidently",
        "Build and customize pivot tables for multi-dimensional analysis",
        "Design clean charts and single-page dashboards in Sheets/Excel",
        "Use data validation and conditional formatting for cleaner data entry",
        "Automate repetitive tasks with basic macros and Google Apps Script",
      ],
      sections: [
        {
          id: "2.1",
          title: "Core Formulas",
          topics: [
            "VLOOKUP, HLOOKUP, INDEX-MATCH, and XLOOKUP",
            "Conditional logic: IF, IFS, AND, OR, nested IFs",
            "SUMIF/SUMIFS, COUNTIF/COUNTIFS, AVERAGEIF/AVERAGEIFS",
            "Text functions: LEFT, RIGHT, MID, TRIM, CONCATENATE, TEXTSPLIT",
            "Date/time functions: DATEDIF, EOMONTH, NETWORKDAYS, TODAY, NOW",
            "Array formulas and dynamic arrays (SORT, FILTER, UNIQUE)",
            "Error handling with IFERROR and IFNA",
            "Absolute vs relative cell references",
          ],
        },
        {
          id: "2.2",
          title: "Pivot Tables",
          topics: [
            "Building pivot tables from raw transactional data",
            "Grouping by date, number ranges, and custom categories",
            "Calculated fields and calculated items",
            "Value field settings: sum, count, average, % of total, running total",
            "Slicers and timelines for interactive filtering",
            "Pivot charts linked to pivot tables",
            "Refreshing and maintaining pivot tables with growing data",
          ],
        },
        {
          id: "2.3",
          title: "Charts & Dashboards",
          topics: [
            "Choosing the right chart type for the message (bar, line, scatter, waterfall)",
            "Combo charts and dual-axis charts",
            "Sparklines for compact trend visualization",
            "Conditional formatting for heatmaps and KPI flags",
            "Building a single-page interactive dashboard with slicers",
            "Data validation dropdowns for dynamic dashboard controls",
            "Protecting sheets and cells for shared workbooks",
          ],
        },
        {
          id: "2.4",
          title: "Automation & Data Prep in Spreadsheets",
          topics: [
            "Text-to-columns and Flash Fill for quick cleanup",
            "Removing duplicates and handling blank cells",
            "Power Query in Excel for repeatable data transformations",
            "Recording and editing basic macros in Excel",
            "Introduction to Google Apps Script for automating Sheets tasks",
            "Importing data from CSV, web, and Google Forms into Sheets",
          ],
        },
      ],
      exercises: [
        "Build an XLOOKUP-based sales lookup workbook across 3 sheets",
        "Create a pivot table with calculated fields from a raw sales export",
        "Design a one-page KPI dashboard with slicers and conditional formatting",
        "Clean a messy dataset using Text-to-Columns, Flash Fill, and Power Query",
        "Record a macro that formats a weekly report automatically",
      ],
      assignments: [
        "Submit a complete sales analysis workbook with pivot tables and charts",
        "Build and share an interactive KPI dashboard for a sample retail dataset",
      ],
      projects: [
        "Retail Sales Dashboard built entirely in Excel/Google Sheets",
      ],
      outcomes: [
        "Writes advanced spreadsheet formulas fluently",
        "Builds pivot tables and pivot charts for multi-dimensional analysis",
        "Designs clean, interactive spreadsheet dashboards",
        "Automates repetitive spreadsheet tasks with Power Query and macros",
      ],
      assessment: "Dashboard workbook graded on formula accuracy, pivot table design, and visual clarity",
    },
    {
      number: 3,
      title: "SQL Fundamentals",
      overview: "Learn to query relational databases confidently, from basic filtering to joins and aggregation, using real multi-table datasets.",
      objectives: [
        "Write SELECT queries with filtering, sorting, and limiting",
        "Join multiple tables correctly using INNER, LEFT, RIGHT, and FULL joins",
        "Aggregate data with GROUP BY and HAVING clauses",
        "Understand basic relational data modeling concepts",
        "Use a SQL client (DBeaver/pgAdmin) against a real Postgres database",
      ],
      sections: [
        {
          id: "3.1",
          title: "Query Basics",
          topics: [
            "SELECT, FROM, WHERE clause fundamentals",
            "Filtering with comparison, LIKE, IN, BETWEEN, and IS NULL",
            "ORDER BY for single and multi-column sorting",
            "LIMIT and OFFSET for pagination",
            "DISTINCT for unique value extraction",
            "Basic arithmetic and string concatenation in SELECT",
            "Aliasing columns and tables with AS",
            "Comments and query formatting best practices",
          ],
        },
        {
          id: "3.2",
          title: "Joins & Aggregations",
          topics: [
            "INNER JOIN vs LEFT JOIN vs RIGHT JOIN vs FULL OUTER JOIN",
            "Self joins and cross joins",
            "Joining 3+ tables in a single query",
            "GROUP BY with COUNT, SUM, AVG, MIN, MAX",
            "HAVING vs WHERE for filtering aggregated results",
            "CASE WHEN statements for conditional logic in queries",
            "UNION and UNION ALL for combining result sets",
          ],
        },
        {
          id: "3.3",
          title: "Data Modeling",
          topics: [
            "Star schema: fact tables and dimension tables",
            "Primary keys, foreign keys, and referential integrity",
            "Normalization basics (1NF, 2NF, 3NF) and when to denormalize",
            "Entity-relationship diagrams (ERDs) for schema design",
            "One-to-many and many-to-many relationships",
            "Designing a schema for an e-commerce or SaaS dataset",
          ],
        },
      ],
      exercises: [
        "Write 10 SELECT/WHERE/ORDER BY queries against a sample sales database",
        "Join a customers, orders, and products table to answer 5 business questions",
        "Use GROUP BY and HAVING to find top customers by revenue",
        "Draw an ERD for a simplified e-commerce schema",
      ],
      assignments: [
        "Submit a SQL query pack answering 15 business questions from a shared schema",
        "Design and document a star schema for a chosen business domain",
      ],
      projects: [
        "E-commerce SQL Query Portfolio with 15+ solved business questions",
      ],
      outcomes: [
        "Writes correct SELECT, WHERE, and ORDER BY queries",
        "Confidently joins multiple tables to answer business questions",
        "Aggregates and filters grouped data with GROUP BY/HAVING",
        "Understands relational data modeling and star schemas",
      ],
      assessment: "SQL query pack graded for correctness, efficiency, and readability",
    },
    {
      number: 4,
      title: "Advanced SQL",
      overview: "Push SQL skills further with window functions, CTEs, subqueries, and query performance tuning against realistic large datasets.",
      objectives: [
        "Use window functions to solve ranking and running-total problems",
        "Write and structure queries with CTEs for readability",
        "Use subqueries and correlated subqueries appropriately",
        "Read query execution plans and apply basic performance tuning",
        "Analyze real-world e-commerce, fintech, and SaaS datasets end to end",
      ],
      sections: [
        {
          id: "4.1",
          title: "Advanced Queries",
          topics: [
            "Window functions: ROW_NUMBER, RANK, DENSE_RANK",
            "Aggregate window functions: SUM, AVG OVER PARTITION BY",
            "LAG and LEAD for period-over-period comparisons",
            "Common Table Expressions (CTEs) and recursive CTEs",
            "Correlated vs non-correlated subqueries",
            "EXISTS and NOT EXISTS for existence checks",
            "Pivoting data with CASE WHEN and crosstab-style queries",
          ],
        },
        {
          id: "4.2",
          title: "Performance",
          topics: [
            "How indexes work (B-tree indexes) and when to add them",
            "Reading EXPLAIN and EXPLAIN ANALYZE query plans",
            "Identifying full table scans vs index scans",
            "Query optimization: avoiding SELECT *, filtering early",
            "Denormalization trade-offs for read-heavy workloads",
            "Materialized views for precomputed aggregates",
          ],
        },
        {
          id: "4.3",
          title: "Real Datasets",
          topics: [
            "Cohort retention analysis on an e-commerce orders table",
            "Fraud/anomaly flagging queries on a fintech transactions dataset",
            "Monthly recurring revenue (MRR) calculation for a SaaS dataset",
            "Customer lifetime value (CLV) queries with window functions",
            "Funnel drop-off analysis using multi-step CTEs",
            "Building a reusable SQL query library for stakeholders",
          ],
        },
      ],
      exercises: [
        "Calculate month-over-month growth using LAG/LEAD window functions",
        "Rewrite a nested subquery as a readable CTE chain",
        "Run EXPLAIN ANALYZE on a slow query and optimize it with an index",
        "Build a cohort retention query for an e-commerce dataset",
      ],
      assignments: [
        "Submit an advanced SQL project computing MRR, churn, and CLV for a SaaS dataset",
        "Document a before/after query optimization case study with execution plans",
      ],
      projects: [
        "SaaS Metrics SQL Engine (MRR, churn, CLV, cohorts) built entirely in SQL",
      ],
      outcomes: [
        "Uses window functions to solve ranking and time-series problems",
        "Writes clean, readable queries using CTEs",
        "Can read execution plans and optimize slow queries",
        "Analyzes realistic e-commerce, fintech, and SaaS datasets confidently",
      ],
      assessment: "SaaS metrics project graded on query correctness, performance, and business relevance",
    },
    {
      number: 5,
      title: "Python for Data (Pandas)",
      overview: "Transition from spreadsheets and SQL to scripted analysis in Python, mastering core language features and the Pandas library for data manipulation.",
      objectives: [
        "Write core Python: variables, control flow, functions, and data structures",
        "Load and manipulate tabular data using Pandas Series and DataFrames",
        "Filter, sort, and group data efficiently in Pandas",
        "Read and write data from CSV, Excel, JSON, APIs, and SQL databases",
        "Debug Python scripts and notebooks confidently",
      ],
      sections: [
        {
          id: "5.1",
          title: "Python Basics",
          topics: [
            "Variables, data types, and type conversion",
            "Lists, tuples, dictionaries, and sets",
            "Control flow: if/elif/else, for loops, while loops",
            "Writing and calling functions with arguments and return values",
            "List comprehensions and lambda functions",
            "Working in Jupyter Notebook and Google Colab",
            "Installing and managing packages with pip and virtual environments",
          ],
        },
        {
          id: "5.2",
          title: "Pandas",
          topics: [
            "Series vs DataFrame objects and their attributes",
            "Selecting data with loc, iloc, and boolean indexing",
            "Filtering rows with multiple conditions",
            "GroupBy, aggregate, and transform operations",
            "Sorting with sort_values and sort_index",
            "Creating and modifying columns with apply and vectorized operations",
            "Handling categorical data with astype and pd.Categorical",
          ],
        },
        {
          id: "5.3",
          title: "IO",
          topics: [
            "Reading and writing CSV and Excel files with read_csv/to_csv",
            "Working with JSON data and nested structures",
            "Pulling data from REST APIs with the requests library",
            "Connecting Pandas to SQL databases with SQLAlchemy",
            "Chunked reading for large files",
            "Combining multiple data sources into a single DataFrame",
          ],
        },
      ],
      exercises: [
        "Write 10 small Python functions covering loops, conditionals, and comprehensions",
        "Load a CSV into Pandas and answer 10 questions using filtering and groupby",
        "Pull data from a public REST API and load it into a DataFrame",
        "Connect Pandas to a Postgres database and query a table into a DataFrame",
      ],
      assignments: [
        "Submit a Jupyter notebook analyzing a real dataset end to end in Pandas",
        "Build a small ETL script that pulls from an API, transforms, and saves to CSV",
      ],
      projects: [
        "API-to-DataFrame Pipeline Notebook with cleaned, analysis-ready output",
      ],
      outcomes: [
        "Writes core Python confidently for data tasks",
        "Manipulates DataFrames using filtering, sorting, and groupby",
        "Reads and writes data across CSV, Excel, JSON, APIs, and SQL",
        "Debugs and iterates on notebooks efficiently",
      ],
      assessment: "Notebook project graded on code correctness, readability, and depth of analysis",
    },
    {
      number: 6,
      title: "Data Cleaning & Wrangling",
      overview: "Master the unglamorous but critical skill of turning messy real-world data into a clean, reliable dataset ready for analysis.",
      objectives: [
        "Identify and handle missing values using appropriate strategies",
        "Detect and treat duplicates and outliers systematically",
        "Reshape and merge datasets from multiple sources",
        "Enforce consistent data types and formats",
        "Build reproducible cleaning workflows with notebooks and scripts",
      ],
      sections: [
        {
          id: "6.1",
          title: "Cleaning",
          topics: [
            "Identifying missing values with isna/isnull and visualizing missingness",
            "Strategies for missing data: drop, fill, interpolate, impute with mean/median",
            "Detecting and removing duplicate rows",
            "Outlier detection with IQR, z-scores, and visual methods (boxplots)",
            "Fixing inconsistent data types (strings vs numbers vs dates)",
            "Standardizing categorical values (typos, casing, whitespace)",
            "Validating data against business rules (e.g., negative prices, future dates)",
          ],
        },
        {
          id: "6.2",
          title: "Transformations",
          topics: [
            "Merging DataFrames with merge (inner, left, right, outer)",
            "Concatenating DataFrames vertically and horizontally",
            "Pivoting and melting data with pivot_table and melt",
            "Reshaping wide-to-long and long-to-wide formats",
            "Binning continuous variables with pd.cut and pd.qcut",
            "Creating derived columns and feature engineering basics",
            "Working with dates: parsing, resampling, and time zone handling",
          ],
        },
        {
          id: "6.3",
          title: "Reproducibility",
          topics: [
            "Structuring cleaning logic into reusable functions and scripts",
            "Documenting assumptions and cleaning decisions inline",
            "Version-controlling notebooks and datasets with Git and Git LFS",
            "Separating raw data from cleaned/processed data folders",
            "Writing data quality checks and assertions",
            "Logging cleaning steps for audit and handoff",
          ],
        },
      ],
      exercises: [
        "Clean a messy CSV with missing values, duplicates, and inconsistent formats",
        "Detect and handle outliers in a sales dataset using IQR and z-scores",
        "Merge 3 related datasets (customers, orders, products) into one clean table",
        "Write a reusable Python cleaning function applied to 2 different datasets",
      ],
      assignments: [
        "Submit a before/after data cleaning report with documented decisions",
        "Build a reproducible cleaning script for a multi-source dataset",
      ],
      projects: [
        "Messy-to-Clean Dataset Pipeline with full documentation of cleaning logic",
      ],
      outcomes: [
        "Systematically identifies and handles missing values and outliers",
        "Merges and reshapes multi-source datasets correctly",
        "Enforces consistent types and formats across a dataset",
        "Builds reproducible, documented cleaning workflows",
      ],
      assessment: "Cleaning pipeline graded on correctness, reproducibility, and documentation quality",
    },
    {
      number: 7,
      title: "Exploratory Data Analysis (EDA)",
      overview: "Learn a structured approach to exploring new datasets and turning raw variables into visual, business-relevant insights.",
      objectives: [
        "Follow a repeatable EDA workflow from question to insight",
        "Perform univariate, bivariate, and multivariate analysis",
        "Create clear, appropriate visualizations with matplotlib, seaborn, and plotly",
        "Summarize findings for a non-technical business audience",
        "Identify patterns, trends, and anomalies in a new dataset",
      ],
      sections: [
        {
          id: "7.1",
          title: "EDA Workflow",
          topics: [
            "Framing the guiding question before opening the dataset",
            "Initial data profiling: shape, dtypes, summary statistics, missingness",
            "Univariate analysis: distributions, histograms, value counts",
            "Bivariate analysis: scatter plots, correlation, grouped comparisons",
            "Multivariate analysis: pair plots, facet grids, heatmaps",
            "Iterating between hypotheses and visual checks",
            "Automated EDA tools: pandas-profiling/ydata-profiling and Sweetviz",
          ],
        },
        {
          id: "7.2",
          title: "Visualization",
          topics: [
            "matplotlib fundamentals: figures, axes, subplots",
            "seaborn for statistical visualizations: distplot, boxplot, violinplot, heatmap",
            "plotly for interactive charts and dashboards",
            "Choosing chart types for the message: comparison, distribution, relationship, composition",
            "Color theory and accessibility in data visualization",
            "Annotating charts for clarity (titles, labels, callouts)",
            "Avoiding common chart misleading practices (truncated axes, 3D pie charts)",
          ],
        },
        {
          id: "7.3",
          title: "Insights",
          topics: [
            "Translating statistical findings into plain-language business insights",
            "Structuring an insight: observation, evidence, implication, recommendation",
            "Prioritizing insights by business impact",
            "Building an EDA summary notebook/report for stakeholders",
            "Common EDA pitfalls: overfitting narratives, cherry-picking, ignoring context",
          ],
        },
      ],
      exercises: [
        "Run a full EDA workflow on an unfamiliar dataset and write 5 key insights",
        "Generate an automated profiling report with ydata-profiling",
        "Build 5 different chart types in seaborn for the same dataset",
        "Create an interactive plotly dashboard exploring 3 variables",
      ],
      assignments: [
        "Submit a complete EDA notebook and a 1-page insight summary for stakeholders",
        "Critique a poorly designed chart and redesign it with best practices",
      ],
      projects: [
        "Exploratory Data Analysis Report on a real-world open dataset",
      ],
      outcomes: [
        "Follows a structured, repeatable EDA workflow",
        "Builds clear univariate, bivariate, and multivariate visualizations",
        "Uses matplotlib, seaborn, and plotly appropriately",
        "Communicates data insights in business-friendly language",
      ],
      assessment: "EDA notebook and summary graded on analytical depth and communication clarity",
    },
    {
      number: 8,
      title: "Statistics for Analysts",
      overview: "Build the statistical foundation every analyst needs: descriptive statistics, inferential reasoning, and rigorous A/B testing.",
      objectives: [
        "Compute and interpret descriptive statistics and distributions",
        "Apply sampling theory and confidence intervals correctly",
        "Run and interpret common hypothesis tests",
        "Design and analyze A/B tests with statistical rigor",
        "Avoid common statistical pitfalls in business analysis",
      ],
      sections: [
        {
          id: "8.1",
          title: "Descriptive Stats",
          topics: [
            "Mean, median, and mode and when each is appropriate",
            "Variance, standard deviation, and coefficient of variation",
            "Skewness and kurtosis in distributions",
            "Normal, binomial, Poisson, and uniform distributions",
            "Percentiles, quartiles, and box plot interpretation",
            "Z-scores and standardization",
          ],
        },
        {
          id: "8.2",
          title: "Inferential Stats",
          topics: [
            "Population vs sample and sampling methods",
            "The Central Limit Theorem in practice",
            "Confidence intervals for means and proportions",
            "Hypothesis testing framework: null vs alternative hypothesis",
            "t-tests (one-sample, two-sample, paired) and their assumptions",
            "Chi-square tests for categorical data",
            "p-values, significance levels, and Type I/Type II errors",
          ],
        },
        {
          id: "8.3",
          title: "A/B Testing",
          topics: [
            "Designing a valid A/B test: randomization, sample size, duration",
            "Calculating required sample size and statistical power",
            "Analyzing results with t-tests and confidence intervals",
            "Statistical significance vs practical/business significance",
            "Common pitfalls: peeking, novelty effects, multiple comparisons",
            "Reporting A/B test results to stakeholders",
          ],
        },
      ],
      exercises: [
        "Calculate descriptive statistics and identify distribution shape for a dataset",
        "Build a 95% confidence interval for a sample mean and proportion",
        "Run a two-sample t-test comparing two groups in Python (scipy.stats)",
        "Design an A/B test plan including sample size calculation for a product change",
      ],
      assignments: [
        "Submit a full A/B test analysis report with hypothesis, results, and recommendation",
        "Write a short explainer translating a p-value result for a non-technical stakeholder",
      ],
      projects: [
        "A/B Test Analysis Report for a simulated product experiment",
      ],
      outcomes: [
        "Computes and interprets descriptive statistics confidently",
        "Applies confidence intervals and hypothesis tests correctly",
        "Designs and analyzes statistically sound A/B tests",
        "Avoids common statistical misinterpretation pitfalls",
      ],
      assessment: "A/B test report graded on statistical rigor and clarity of business recommendation",
    },
    {
      number: 9,
      title: "Business Intelligence: Power BI",
      overview: "Build professional, interactive BI dashboards in Power BI, from data modeling and DAX to publishing and sharing with stakeholders.",
      objectives: [
        "Build a Power BI data model connecting multiple tables",
        "Write core DAX measures and calculated columns",
        "Design interactive dashboards with drill-through and bookmarks",
        "Apply row-level security to control data access",
        "Publish and share Power BI reports through workspaces",
      ],
      sections: [
        {
          id: "9.1",
          title: "Power BI Core",
          topics: [
            "Power BI Desktop interface: Report, Data, and Model views",
            "Connecting to data sources: Excel, SQL, CSV, and web APIs",
            "Power Query Editor for shaping and transforming data",
            "Building a relational data model with relationships between tables",
            "DAX basics: calculated columns vs measures",
            "Core DAX functions: SUM, CALCULATE, FILTER, ALL, RELATED",
            "Time intelligence functions: TOTALYTD, SAMEPERIODLASTYEAR, DATEADD",
          ],
        },
        {
          id: "9.2",
          title: "Dashboards",
          topics: [
            "Choosing and configuring visuals: cards, bar/line charts, matrix, maps",
            "Building KPI cards with target comparisons",
            "Slicers and cross-filtering between visuals",
            "Drill-through pages for detailed views",
            "Bookmarks and buttons for interactive navigation",
            "Conditional formatting and custom tooltips",
            "Designing for mobile layout in Power BI",
          ],
        },
        {
          id: "9.3",
          title: "Sharing",
          topics: [
            "Publishing reports to Power BI Service workspaces",
            "Setting up scheduled data refresh",
            "Row-level security (RLS) roles for restricted data access",
            "Sharing dashboards via apps and direct links",
            "Power BI mobile app for on-the-go reporting",
            "Version control and report lifecycle management",
          ],
        },
      ],
      exercises: [
        "Build a Power BI data model from 3 related tables with correct relationships",
        "Write 5 DAX measures including a time-intelligence calculation",
        "Design a dashboard page with slicers, KPI cards, and drill-through",
        "Set up row-level security for a regional sales dataset",
      ],
      assignments: [
        "Submit a published Power BI dashboard analyzing a real or provided dataset",
        "Document 5 DAX measures used in your dashboard with explanations",
      ],
      projects: [
        "Power BI Sales/Operations Dashboard with DAX measures and RLS",
      ],
      outcomes: [
        "Builds a correct, well-structured Power BI data model",
        "Writes functional DAX measures for business metrics",
        "Designs interactive, professional-looking dashboards",
        "Publishes and secures reports for stakeholder consumption",
      ],
      assessment: "Power BI dashboard graded on data model correctness, DAX quality, and interactivity",
    },
    {
      number: 10,
      title: "Business Intelligence: Tableau & Looker Studio",
      overview: "Expand BI fluency to Tableau's visual analytics engine and the free, widely-used Looker Studio for lightweight reporting.",
      objectives: [
        "Connect Tableau to multiple data sources and build calculated fields",
        "Use Tableau's Marks card to build rich, layered visualizations",
        "Build free dashboards and reports in Looker Studio",
        "Blend multiple data sources within Looker Studio",
        "Choose the right BI tool for a given business context and budget",
      ],
      sections: [
        {
          id: "10.1",
          title: "Tableau",
          topics: [
            "Connecting Tableau to Excel, CSV, and SQL data sources",
            "Dimensions vs measures and the Tableau data pane",
            "The Marks card: color, size, label, detail, and tooltip",
            "Calculated fields and table calculations",
            "Filters, parameters, and dashboard actions",
            "Building dual-axis and combo charts in Tableau",
            "Publishing to Tableau Public and Tableau Server basics",
          ],
        },
        {
          id: "10.2",
          title: "Looker Studio",
          topics: [
            "Connecting Looker Studio to Google Sheets, BigQuery, and CSV",
            "Building charts, scorecards, and tables in Looker Studio",
            "Data blending across multiple sources",
            "Community connectors for third-party data (ads platforms, CRMs)",
            "Filter controls and interactive report design",
            "Sharing and embedding free Looker Studio dashboards",
          ],
        },
      ],
      exercises: [
        "Build a Tableau dashboard using calculated fields and dashboard actions",
        "Recreate the same dashboard in Looker Studio and compare tradeoffs",
        "Blend two data sources in Looker Studio into one combined chart",
        "Publish a dashboard to Tableau Public and share the link",
      ],
      assignments: [
        "Submit a Tableau dashboard analyzing a chosen business dataset",
        "Submit a free Looker Studio report suitable for a small business client",
      ],
      projects: [
        "Comparative BI Project: same dataset visualized in Tableau and Looker Studio",
      ],
      outcomes: [
        "Builds calculated fields and rich visuals in Tableau",
        "Builds and blends data sources in Looker Studio",
        "Understands strengths and tradeoffs of different BI tools",
        "Publishes and shares BI dashboards professionally",
      ],
      assessment: "Comparative dashboard project graded on visual design and correct use of each tool's features",
    },
    {
      number: 11,
      title: "Data Storytelling & Reporting",
      overview: "Learn to turn analysis into narrative — designing dashboards and reports that persuade and drive action from busy stakeholders.",
      objectives: [
        "Structure a data story using a clear narrative arc",
        "Apply visual hierarchy, color, and whitespace principles to dashboard design",
        "Tailor reporting cadence and depth to different stakeholder types",
        "Build recurring executive reports and alerting systems",
        "Present findings confidently in a live stakeholder meeting",
      ],
      sections: [
        {
          id: "11.1",
          title: "Storytelling",
          topics: [
            "Narrative arcs for data presentations: setup, conflict, resolution",
            "The pyramid principle: lead with the conclusion",
            "Framing insights for different stakeholder personas (exec, ops, product)",
            "One-slide, one-message rule for presentations",
            "Using annotations and callouts to guide the viewer's eye",
            "Turning a dashboard into a narrated walkthrough",
          ],
        },
        {
          id: "11.2",
          title: "Dashboard Design",
          topics: [
            "Visual hierarchy: size, position, and contrast to guide attention",
            "Color theory for dashboards: sequential, diverging, categorical palettes",
            "Whitespace and grid alignment for scannability",
            "Typography and labeling best practices",
            "Avoiding chartjunk and unnecessary decoration",
            "Accessibility considerations (color blindness, contrast ratios)",
          ],
        },
        {
          id: "11.3",
          title: "Executive Reporting",
          topics: [
            "Designing weekly, monthly, and quarterly reporting cadences",
            "Building automated alerts for KPI thresholds",
            "Writing an executive summary alongside a dashboard",
            "Version-controlling and archiving recurring reports",
            "Handling stakeholder questions and follow-up requests",
            "Presenting data findings live with confidence",
          ],
        },
      ],
      exercises: [
        "Rewrite a data-dump slide into a pyramid-principle, one-message slide",
        "Redesign a cluttered dashboard applying visual hierarchy and color principles",
        "Draft a weekly executive report template with an automated alert rule",
        "Deliver a 5-minute mock presentation of a dashboard to a stakeholder persona",
      ],
      assignments: [
        "Submit a redesigned dashboard with a before/after rationale",
        "Submit a written executive summary accompanying a chosen dashboard",
      ],
      projects: [
        "Executive Reporting Package: dashboard + narrative summary + alert plan",
      ],
      outcomes: [
        "Structures insights using a clear narrative arc",
        "Designs dashboards with strong visual hierarchy and clarity",
        "Builds recurring, stakeholder-appropriate reporting cadences",
        "Presents data findings persuasively and confidently",
      ],
      assessment: "Reporting package graded on narrative clarity, design quality, and stakeholder fit",
    },
    {
      number: 12,
      title: "Data Warehousing & Pipelines",
      overview: "Understand how data moves and is stored at scale in modern companies, from cloud warehouses to ELT pipelines and transformation tools.",
      objectives: [
        "Explain the role of a data warehouse in a modern data stack",
        "Query and manage data in a cloud warehouse (BigQuery/Snowflake)",
        "Distinguish ETL from ELT and when each is used",
        "Build a simple transformation model using dbt concepts",
        "Understand data ingestion tools like Airbyte and Fivetran",
      ],
      sections: [
        {
          id: "12.1",
          title: "Warehouses",
          topics: [
            "What a data warehouse is and why companies use one",
            "Cloud warehouse options: BigQuery, Snowflake, Redshift",
            "Running analytical queries in BigQuery/Snowflake",
            "Postgres as a lightweight analytics warehouse",
            "Partitioning and clustering for query performance",
            "Cost management and query optimization in cloud warehouses",
          ],
        },
        {
          id: "12.2",
          title: "ELT/ETL",
          topics: [
            "ETL vs ELT: when transformation happens and why it matters",
            "Introduction to dbt: models, sources, and the DAG of transformations",
            "Writing a basic dbt model with SELECT and ref()",
            "dbt tests for data quality (unique, not_null, relationships)",
            "Ingestion tools: Airbyte and Fivetran for automated data pulls",
            "Orchestration basics: scheduling pipelines (cron, Airflow overview)",
            "The modern data stack: source to warehouse to BI",
          ],
        },
      ],
      exercises: [
        "Run analytical queries against a public BigQuery dataset",
        "Set up a free Snowflake or BigQuery sandbox and load a sample table",
        "Write a basic dbt model transforming raw data into a clean table",
        "Add dbt tests to validate uniqueness and null constraints",
      ],
      assignments: [
        "Submit a working dbt project with at least 2 models and tests",
        "Write a short explainer comparing ETL and ELT for a real use case",
      ],
      projects: [
        "Mini Modern Data Stack: raw data ingested, transformed with dbt, queried in warehouse",
      ],
      outcomes: [
        "Understands the role and architecture of a data warehouse",
        "Runs and optimizes queries in a cloud warehouse",
        "Builds and tests basic dbt transformation models",
        "Understands data ingestion and orchestration at a conceptual level",
      ],
      assessment: "dbt project graded on model correctness, test coverage, and documentation",
    },
    {
      number: 13,
      title: "Product Analytics",
      overview: "Apply analytics skills to product and growth questions, learning the metrics and tools that power modern product teams.",
      objectives: [
        "Define and apply a North Star metric framework",
        "Analyze acquisition, activation, retention, and revenue metrics",
        "Use product analytics tools to explore user behavior",
        "Build and interpret funnel and cohort analyses",
        "Turn product analytics findings into actionable recommendations",
      ],
      sections: [
        {
          id: "13.1",
          title: "Product Metrics",
          topics: [
            "North Star metric selection and framework",
            "AARRR framework: Acquisition, Activation, Retention, Referral, Revenue",
            "DAU/MAU, stickiness ratio, and engagement metrics",
            "Retention curves and cohort retention analysis",
            "Feature adoption and usage metrics",
            "Defining and tracking event taxonomies",
          ],
        },
        {
          id: "13.2",
          title: "Tools",
          topics: [
            "PostHog for event tracking, funnels, and session replay",
            "Amplitude for behavioral analytics and cohorting",
            "Mixpanel for event-based product analysis",
            "Setting up event tracking plans with a data dictionary",
            "Connecting product analytics tools to a warehouse",
            "Comparing tool tradeoffs by team size and budget",
          ],
        },
        {
          id: "13.3",
          title: "Funnels & Cohorts",
          topics: [
            "Building conversion funnels and identifying drop-off points",
            "Cohort analysis by signup date, acquisition channel, or plan type",
            "Segmenting users by behavior for targeted insights",
            "Diagnosing why a funnel step is underperforming",
            "Turning funnel/cohort findings into product recommendations",
            "Communicating product analytics insights to product managers",
          ],
        },
      ],
      exercises: [
        "Define a North Star metric and supporting metrics for a sample app",
        "Build a signup-to-activation funnel in PostHog or a mock dataset",
        "Run a cohort retention analysis and identify the biggest drop-off point",
        "Write a one-page product analytics insight memo with a recommendation",
      ],
      assignments: [
        "Submit a full product analytics report including funnel and cohort analysis",
        "Design an event tracking plan/data dictionary for a sample product feature",
      ],
      projects: [
        "Product Analytics Report: funnel, cohort retention, and growth recommendations",
      ],
      outcomes: [
        "Applies the North Star and AARRR frameworks to real products",
        "Uses product analytics tools to explore user behavior",
        "Builds and interprets funnel and cohort analyses",
        "Turns behavioral data into concrete product recommendations",
      ],
      assessment: "Product analytics report graded on metric selection, analysis rigor, and recommendation quality",
    },
    {
      number: 14,
      title: "Intro to Machine Learning for Analysts",
      overview: "Give analysts working fluency with machine learning concepts and common models so they can collaborate with data scientists and apply light ML themselves.",
      objectives: [
        "Distinguish supervised, unsupervised, and reinforcement learning",
        "Correctly split data into train/test sets and evaluate models",
        "Build and interpret linear/logistic regression and decision tree models",
        "Apply clustering for unsupervised segmentation problems",
        "Understand basic model deployment and scoring concepts",
      ],
      sections: [
        {
          id: "14.1",
          title: "ML Concepts",
          topics: [
            "Supervised vs unsupervised vs reinforcement learning",
            "Train/test/validation splits and why they matter",
            "Overfitting vs underfitting and the bias-variance tradeoff",
            "Evaluation metrics: accuracy, precision, recall, F1, RMSE, R-squared",
            "Feature engineering basics for ML models",
            "Cross-validation for robust model evaluation",
          ],
        },
        {
          id: "14.2",
          title: "Common Models",
          topics: [
            "Linear regression for continuous prediction problems",
            "Logistic regression for binary classification",
            "Decision trees and how they split data",
            "Random forests as an ensemble improvement over single trees",
            "K-means clustering for customer/user segmentation",
            "Using scikit-learn to fit, predict, and evaluate models",
          ],
        },
        {
          id: "14.3",
          title: "Deployment Basics",
          topics: [
            "Model as a service: exposing a model behind a simple API",
            "Batch scoring: applying a model to a full table on a schedule",
            "Saving and loading models with pickle/joblib",
            "Monitoring model performance drift over time",
            "Collaborating with data scientists: what analysts contribute to ML projects",
          ],
        },
      ],
      exercises: [
        "Build a linear regression model to predict sales from historical data",
        "Build a logistic regression churn model and evaluate precision/recall",
        "Run K-means clustering to segment customers into 4 groups",
        "Save a trained model and write a small script to batch-score new data",
      ],
      assignments: [
        "Submit a churn prediction notebook with model evaluation metrics",
        "Submit a customer segmentation notebook using K-means with business interpretation",
      ],
      projects: [
        "Churn Prediction & Customer Segmentation Notebook using scikit-learn",
      ],
      outcomes: [
        "Understands core machine learning concepts and terminology",
        "Builds and evaluates regression, classification, and clustering models",
        "Correctly splits and validates data for model training",
        "Understands basic model deployment and scoring workflows",
      ],
      assessment: "ML notebook graded on modeling correctness, evaluation rigor, and business interpretation",
    },
    {
      number: 15,
      title: "Portfolio, Freelancing & Interviews",
      overview: "Package all prior work into a professional portfolio, prepare for technical interviews, and explore freelance and consulting paths in analytics.",
      objectives: [
        "Build a public portfolio showcasing analytics projects",
        "Write clear case studies that explain business impact",
        "Practice SQL take-homes, case studies, and behavioral interview questions",
        "Set up freelance profiles and pricing for data consulting",
        "Develop a personal brand and networking strategy in analytics",
      ],
      sections: [
        {
          id: "15.1",
          title: "Portfolio",
          topics: [
            "Structuring a GitHub profile with pinned analytics repositories",
            "Writing effective READMEs for data projects",
            "Building Notion or web-based case studies with problem, process, impact",
            "Participating in Kaggle competitions and datasets for portfolio pieces",
            "Choosing your 3-5 strongest projects to feature",
            "Personal website/portfolio site options for analysts",
          ],
        },
        {
          id: "15.2",
          title: "Interviews",
          topics: [
            "Common SQL take-home test formats and how to approach them",
            "Case study interviews: structuring your answer out loud",
            "Behavioral interview questions using the STAR method",
            "Explaining a past project clearly to a non-technical interviewer",
            "Salary negotiation basics for analytics roles",
            "Mock interview practice and feedback loops",
          ],
        },
        {
          id: "15.3",
          title: "Freelance",
          topics: [
            "Setting up profiles on Upwork and Contra for data consulting",
            "Pricing analytics services: hourly vs project-based vs retainer",
            "Writing proposals that win data analytics gigs",
            "Scoping a client project and setting expectations",
            "Delivering client dashboards and reports professionally",
            "Building repeat business and referrals as a freelance analyst",
          ],
        },
      ],
      exercises: [
        "Write a case study for your best project (problem, process, impact)",
        "Complete a mock SQL take-home test under a time limit",
        "Do a mock behavioral interview using the STAR method",
        "Write a freelance proposal for a sample client brief",
      ],
      assignments: [
        "Submit a live portfolio (GitHub + case study site) with at least 5 projects",
        "Submit a completed Upwork/Contra profile draft for review",
      ],
      projects: [
        "Complete Public Analytics Portfolio with 5+ documented case studies",
      ],
      outcomes: [
        "Has a live, professional analytics portfolio",
        "Can confidently handle SQL, case study, and behavioral interviews",
        "Has a functioning freelance profile and pricing strategy",
        "Can explain past projects clearly to technical and non-technical audiences",
      ],
      assessment: "Portfolio and mock interview performance reviewed against an industry-readiness rubric",
    },
    {
      number: 16,
      title: "Capstone: End-to-End Analytics Product",
      overview: "Apply everything learned in the diploma to design, build, and ship a complete analytics product, from a business question to a deployed dashboard and executive report.",
      objectives: [
        "Frame a real business question into a scoped analytics project",
        "Build an ingest-clean-model-serve data pipeline end to end",
        "Apply appropriate statistical or ML techniques to answer the question",
        "Design and publish an interactive stakeholder-ready dashboard",
        "Present findings and recommendations in an executive-ready report",
      ],
      sections: [
        {
          id: "16.1",
          title: "Question",
          topics: [
            "Selecting a real or realistic business problem and dataset",
            "Framing the business question and success criteria",
            "Defining the key metrics the project will move or explain",
            "Scoping the project timeline and deliverables",
            "Identifying data sources and access requirements",
          ],
        },
        {
          id: "16.2",
          title: "Pipeline",
          topics: [
            "Ingesting data from source files, APIs, or a database",
            "Cleaning and transforming data with Python/Pandas or SQL/dbt",
            "Modeling the data into an analysis-ready schema",
            "Applying statistical tests or a light ML model where appropriate",
            "Serving the final data to a BI tool or database for reporting",
            "Documenting the pipeline for reproducibility",
          ],
        },
        {
          id: "16.3",
          title: "Dashboard & Story",
          topics: [
            "Designing an interactive dashboard in Power BI, Tableau, or Looker Studio",
            "Applying dashboard design and storytelling principles from Week 11",
            "Writing an executive-ready summary report of findings",
            "Preparing and rehearsing a final capstone presentation",
            "Publishing/deploying the dashboard for public or portfolio access",
            "Incorporating feedback and iterating on the final deliverable",
          ],
        },
      ],
      exercises: [
        "Write a one-page project charter defining the business question and scope",
        "Build and test the data pipeline in stages with checkpoints",
        "Design 3 dashboard layout wireframes before building the final version",
        "Run a peer review of your dashboard and incorporate feedback",
      ],
      assignments: [
        "Submit a working end-to-end pipeline with documentation",
        "Submit the final capstone dashboard and executive report",
      ],
      projects: [
        "Deployed Analytics Product with Interactive Dashboard + Executive Report",
      ],
      outcomes: [
        "Scopes and delivers a full analytics project independently",
        "Builds a working ingest-clean-model-serve data pipeline",
        "Publishes a polished, interactive stakeholder dashboard",
        "Presents findings and recommendations at a professional standard",
      ],
      assessment: "Capstone graded on business framing, technical execution, dashboard quality, and presentation",
    },
  ],
};
