import type { CourseCurriculum } from "./types";
import img from "@/assets/curriculum/digital-marketing.jpg";

export const digitalMarketing: CourseCurriculum = {
  slug: "digital-marketing",
  title: "Digital Marketing",
  tagline: "Professional Certificate",
  duration: "2 Months (8 Weeks)",
  months: 2,
  totalWeeks: 8,
  level: "Beginner to Job Ready",
  projectsCount: "10+",
  capstone: "1 Full Go-To-Market Campaign",
  goal: "Turn absolute beginners into job-ready digital marketers capable of planning, executing, and measuring full-funnel campaigns across content, social, SEO, paid ads, email, and AI-assisted marketing tools, culminating in a complete go-to-market campaign portfolio piece.",
  overview: "An intensive 8-week professional certificate covering the entire modern digital marketing stack: positioning and audience research, content and copywriting, social media strategy and short-form video, SEO, paid advertising (Meta, Google, TikTok), email marketing and funnels, landing pages and conversion optimization, influencer and community marketing, analytics and attribution, AI marketing tools, and the business of freelancing or running an agency. Students finish with a live portfolio of campaigns and a capstone go-to-market strategy.",
  image: img,
  weeks: [
    {
      number: 1,
      title: "Marketing Fundamentals, Positioning & Audience Research",
      overview: "Establish the strategic foundation of digital marketing: how markets work, how to position a brand, and how to deeply understand the people you are marketing to.",
      objectives: [
        "Explain the core principles of modern digital marketing and the full-funnel model",
        "Build a clear brand positioning statement and value proposition",
        "Develop a rigorous ideal customer profile (ICP) and buyer personas",
        "Map the customer journey from awareness to advocacy",
        "Audit competitors and identify market gaps",
      ],
      sections: [
        {
          id: "1.1",
          title: "Foundations of Digital Marketing",
          topics: [
            "What digital marketing is and how it differs from traditional marketing",
            "The marketing funnel: awareness, consideration, conversion, retention, advocacy",
            "AIDA and See-Think-Do-Care frameworks",
            "Inbound vs outbound marketing",
            "Owned, earned, and paid media explained",
            "The modern marketing channel landscape in 2026",
            "How marketing, sales, and product fit together",
            "Key marketing terminology: CAC, LTV, CTR, CPC, CPM, ROAS, conversion rate",
            "Overview of a full digital marketing career path",
            "Ethics and compliance basics (data privacy, GDPR, CAN-SPAM)",
          ],
        },
        {
          id: "1.2",
          title: "Brand Positioning & Value Proposition",
          topics: [
            "What positioning means and why it drives every marketing decision",
            "Category design and competitive frames of reference",
            "Writing a positioning statement (for X, who Y, our product is Z, unlike A, we B)",
            "Value proposition canvas: pains, gains, and jobs to be done",
            "Differentiation strategies: price, quality, convenience, experience, niche",
            "Brand voice, tone, and personality definition",
            "Messaging hierarchy: core message, pillars, proof points",
            "Positioning workshops and stress-testing with real examples",
          ],
        },
        {
          id: "1.3",
          title: "Audience Research & Ideal Customer Profiles",
          topics: [
            "Quantitative vs qualitative audience research methods",
            "Building an Ideal Customer Profile (ICP) with firmographics and psychographics",
            "Creating detailed buyer personas with goals, objections, and triggers",
            "Customer interview scripts and how to run discovery calls",
            "Survey design with Google Forms and Typeform",
            "Social listening for audience insight (Reddit, forums, comment sections)",
            "Using AnswerThePublic and keyword tools for pain-point discovery",
            "Segmenting audiences by behavior, demographics, and intent",
          ],
        },
        {
          id: "1.4",
          title: "Customer Journey Mapping",
          topics: [
            "Stages of the customer journey and touchpoint identification",
            "Mapping channels to each funnel stage",
            "Micro-moments and intent signals",
            "Content needs at each journey stage",
            "Identifying friction points and drop-off risks",
            "Journey mapping tools and templates",
            "Connecting journey maps to KPIs",
          ],
        },
        {
          id: "1.5",
          title: "Competitive & Market Analysis",
          topics: [
            "How to run a competitor audit across website, social, ads, and content",
            "SWOT analysis applied to marketing strategy",
            "Using SimilarWeb, SEMrush, and Meta Ads Library for competitor research",
            "Identifying market whitespace and underserved segments",
            "Benchmarking pricing, messaging, and channel presence",
            "Building a competitive positioning map",
          ],
        },
      ],
      exercises: [
        "Write a one-paragraph positioning statement for a fictional product",
        "Build a full buyer persona document with goals and objections",
        "Conduct 3 mock customer discovery interviews and summarize insights",
        "Map a full customer journey for an e-commerce brand",
      ],
      assignments: [
        "Deliver a complete ICP and 2 buyer personas for your capstone business idea",
        "Submit a competitive audit of 3 direct competitors with a positioning map",
      ],
      projects: [
        "Brand Positioning & ICP Report for a chosen niche business",
      ],
      outcomes: [
        "Can articulate clear brand positioning and value propositions",
        "Can build data-backed ideal customer profiles and personas",
        "Understands the full marketing funnel and customer journey",
        "Can perform structured competitive research",
      ],
      assessment: "Graded positioning and ICP report reviewed against a rubric covering clarity, evidence, and strategic depth",
    },
    {
      number: 2,
      title: "Content Marketing & Copywriting",
      overview: "Master the craft of writing and producing content that attracts, persuades, and converts across blogs, ads, emails, and social captions.",
      objectives: [
        "Build a content strategy aligned to funnel stages and business goals",
        "Write persuasive copy using proven frameworks",
        "Produce a repeatable content calendar and workflow",
        "Apply storytelling techniques to brand content",
        "Repurpose one piece of content across multiple formats",
      ],
      sections: [
        {
          id: "2.1",
          title: "Content Strategy Fundamentals",
          topics: [
            "Content pillars and topic clusters",
            "Aligning content types to funnel stages (TOFU, MOFU, BOFU)",
            "Content formats: blog, video, podcast, carousel, newsletter, case study",
            "Setting content goals and KPIs (traffic, engagement, leads, shares)",
            "Building an editorial calendar",
            "Content audits and gap analysis",
            "Content briefs and creative briefs for writers/designers",
          ],
        },
        {
          id: "2.2",
          title: "Copywriting Frameworks",
          topics: [
            "AIDA, PAS (Problem-Agitate-Solution), and BAB (Before-After-Bridge)",
            "The 4 U's: Urgent, Unique, Useful, Ultra-specific",
            "Writing compelling headlines and hooks",
            "Features vs benefits and how to translate them",
            "Writing calls-to-action that convert",
            "Objection-handling copy techniques",
            "Voice and tone matching for different brands",
            "Editing copy for clarity, brevity, and rhythm",
          ],
        },
        {
          id: "2.3",
          title: "Storytelling & Brand Narrative",
          topics: [
            "The hero's journey applied to brand storytelling",
            "Customer-as-hero narrative structure",
            "Using case studies and testimonials as story assets",
            "Emotional triggers in marketing copy",
            "Data storytelling: turning numbers into narrative",
            "Building a brand story document",
          ],
        },
        {
          id: "2.4",
          title: "Blog & Long-Form Content Production",
          topics: [
            "Keyword-informed blog outlining",
            "Writing SEO-friendly introductions and subheadings",
            "Formatting for readability: bullet points, short paragraphs, visuals",
            "Internal linking strategy within articles",
            "Editing workflows: self-edit, peer review, style guides",
            "Publishing checklists (meta title, meta description, alt text)",
          ],
        },
        {
          id: "2.5",
          title: "Content Repurposing & Workflow",
          topics: [
            "Turning one blog post into 10+ pieces of content",
            "Repurposing long-form video into shorts, quotes, and carousels",
            "Batch content creation systems",
            "Content calendars and scheduling tools (Notion, Trello, Buffer)",
            "Working with freelance writers and designers",
            "AI-assisted content drafting workflows",
          ],
        },
      ],
      exercises: [
        "Rewrite 5 weak headlines into high-converting ones",
        "Write a PAS-framework ad copy for a real product",
        "Draft a 1200-word SEO blog outline with headers",
        "Repurpose one blog post into 5 social media posts",
      ],
      assignments: [
        "Submit a 4-week content calendar with pillars and formats mapped to funnel stages",
        "Write and submit 3 pieces of copy: a landing page hero, an email, and an ad",
      ],
      projects: [
        "Full Content Strategy & Copywriting Portfolio for the capstone brand",
      ],
      outcomes: [
        "Can build a structured content strategy and calendar",
        "Writes persuasive copy using proven frameworks",
        "Understands storytelling as a conversion tool",
        "Can repurpose content efficiently across channels",
      ],
      assessment: "Portfolio review of copy samples and content calendar graded on strategy alignment and persuasive quality",
    },
    {
      number: 3,
      title: "Social Media Strategy & Short-Form Video",
      overview: "Develop platform-specific strategies for Instagram, TikTok, X, LinkedIn, and YouTube, with hands-on short-form video production and editing.",
      objectives: [
        "Build platform-specific content strategies for 5 major social networks",
        "Understand algorithm mechanics and engagement signals per platform",
        "Script, shoot, and edit short-form video content",
        "Grow an audience organically using proven content formats",
        "Manage a social media content calendar end to end",
      ],
      sections: [
        {
          id: "3.1",
          title: "Platform Strategy: Instagram & TikTok",
          topics: [
            "Instagram algorithm signals: reels, carousels, stories, saves, shares",
            "TikTok algorithm and the For You Page mechanics",
            "Content pillars for Instagram and TikTok growth",
            "Hook writing for the first 3 seconds of video",
            "Trends, sounds, and audio strategy",
            "Hashtag and caption strategy",
            "Posting cadence and optimal timing",
            "Instagram Reels vs TikTok content differences",
          ],
        },
        {
          id: "3.2",
          title: "Platform Strategy: X, LinkedIn & YouTube",
          topics: [
            "X (Twitter) growth: threads, replies, and engagement farming ethics",
            "LinkedIn algorithm and B2B content strategy",
            "Writing LinkedIn posts that drive engagement and leads",
            "YouTube Shorts vs long-form strategy",
            "YouTube SEO: titles, thumbnails, descriptions, tags",
            "Building a personal brand across platforms",
            "Cross-platform content adaptation strategy",
          ],
        },
        {
          id: "3.3",
          title: "Short-Form Video Production",
          topics: [
            "Scripting short-form videos with hook-body-CTA structure",
            "Filming on a smartphone: lighting, framing, audio basics",
            "B-roll and visual storytelling techniques",
            "Editing in CapCut: cuts, captions, transitions, pacing",
            "Adding trending sounds and text overlays",
            "Thumbnail and cover design for videos",
            "Batch filming and content pipelines",
          ],
        },
        {
          id: "3.4",
          title: "Community Management & Engagement",
          topics: [
            "Responding to comments and DMs to build community",
            "Engagement pods and authentic engagement strategies",
            "Handling negative comments and PR moments",
            "Building a content engagement loop",
            "Social listening for community insight",
            "User-generated content campaigns",
          ],
        },
        {
          id: "3.5",
          title: "Social Media Analytics & Growth Tracking",
          topics: [
            "Key metrics: reach, impressions, engagement rate, follower growth",
            "Native analytics tools per platform",
            "Using third-party tools like Metricool and Later",
            "A/B testing content formats and hooks",
            "Building a weekly social performance report",
          ],
        },
      ],
      exercises: [
        "Write 5 scroll-stopping hooks for short-form video",
        "Script and storyboard a 30-second Reel/TikTok",
        "Film and edit one short-form video using CapCut",
        "Write 3 LinkedIn posts for a B2B brand",
      ],
      assignments: [
        "Produce and publish 3 short-form videos with a documented content strategy",
        "Submit a 2-week social media content calendar across 3 platforms",
      ],
      projects: [
        "Multi-Platform Social Media Content Campaign with 5+ produced assets",
      ],
      outcomes: [
        "Can plan platform-specific social strategies",
        "Can script, film, and edit short-form video content",
        "Understands engagement mechanics and community management",
        "Can track and report on social performance metrics",
      ],
      assessment: "Video and campaign deliverables graded on production quality, strategy, and platform fit",
    },
    {
      number: 4,
      title: "Search Engine Optimization (SEO)",
      overview: "Deep dive into technical, on-page, and off-page SEO, keyword research, and using GA4 and Search Console to drive organic growth.",
      objectives: [
        "Perform comprehensive keyword research and search intent mapping",
        "Optimize on-page elements for search visibility",
        "Audit and fix technical SEO issues",
        "Build a link-building and off-page SEO strategy",
        "Use GA4 and Search Console to monitor organic performance",
      ],
      sections: [
        {
          id: "4.1",
          title: "SEO Foundations & Search Intent",
          topics: [
            "How search engines crawl, index, and rank pages",
            "Types of search intent: informational, navigational, transactional, commercial",
            "SERP features: featured snippets, People Also Ask, local pack",
            "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)",
            "Core Web Vitals and ranking factors overview",
            "SEO vs SEM: when to use each",
          ],
        },
        {
          id: "4.2",
          title: "Keyword Research",
          topics: [
            "Using Google Keyword Planner, Ahrefs, and Ubersuggest",
            "Head terms vs long-tail keywords",
            "Search volume, keyword difficulty, and CPC interpretation",
            "Building keyword clusters and topic maps",
            "Competitor keyword gap analysis",
            "Mapping keywords to funnel stages and page types",
          ],
        },
        {
          id: "4.3",
          title: "On-Page SEO",
          topics: [
            "Title tag and meta description optimization",
            "Header tag structure (H1-H3) and keyword placement",
            "URL structure best practices",
            "Internal linking strategy and anchor text",
            "Image optimization: alt text, compression, file naming",
            "Content optimization for target keywords without stuffing",
            "Schema markup basics for rich results",
          ],
        },
        {
          id: "4.4",
          title: "Technical SEO",
          topics: [
            "Site speed and Core Web Vitals optimization",
            "Mobile-friendliness and responsive design checks",
            "XML sitemaps and robots.txt configuration",
            "Crawl budget and indexation issues",
            "Fixing 404s, redirects, and duplicate content",
            "Running a technical SEO audit with Screaming Frog",
            "HTTPS, canonical tags, and structured data validation",
          ],
        },
        {
          id: "4.5",
          title: "Off-Page SEO & Link Building",
          topics: [
            "Backlink quality signals: authority, relevance, anchor text",
            "Guest posting and outreach strategies",
            "Digital PR and HARO for link acquisition",
            "Broken link building tactics",
            "Local SEO and Google Business Profile optimization",
            "Analyzing backlink profiles with Ahrefs",
          ],
        },
        {
          id: "4.6",
          title: "Measuring SEO with GA4 & Search Console",
          topics: [
            "Setting up GA4 properties and data streams",
            "Understanding GA4 events, conversions, and engagement metrics",
            "Connecting Search Console to monitor queries and impressions",
            "Tracking organic traffic trends and keyword rankings",
            "Building an SEO performance dashboard",
            "Diagnosing traffic drops using GA4 and Search Console data",
          ],
        },
      ],
      exercises: [
        "Perform keyword research and build a 20-keyword cluster for a niche site",
        "Run a technical SEO audit on a live website using Screaming Frog",
        "Optimize on-page elements for a sample blog post",
        "Set up a GA4 property and configure key events",
      ],
      assignments: [
        "Submit a full SEO audit report (technical, on-page, off-page) for a real website",
        "Build a 3-month keyword-mapped content plan for the capstone brand",
      ],
      projects: [
        "Complete SEO Audit & Optimization Plan with GA4/Search Console setup",
      ],
      outcomes: [
        "Can perform keyword research and search intent mapping",
        "Can audit and fix on-page and technical SEO issues",
        "Understands off-page and link-building strategy",
        "Can configure and interpret GA4 and Search Console data",
      ],
      assessment: "SEO audit report graded on completeness, accuracy, and actionability of recommendations",
    },
    {
      number: 5,
      title: "Paid Advertising: Meta, Google & TikTok Ads",
      overview: "Build, launch, and optimize paid campaigns across Meta Ads, Google Ads, and TikTok Ads, mastering targeting, creative testing, budgeting, and ROAS optimization.",
      objectives: [
        "Set up and structure campaigns in Meta Ads Manager, Google Ads, and TikTok Ads",
        "Build targeting strategies using demographics, interests, and lookalikes",
        "Design and test ad creatives for performance",
        "Manage budgets, bidding strategies, and scaling decisions",
        "Calculate and optimize for ROAS and CPA",
      ],
      sections: [
        {
          id: "5.1",
          title: "Paid Media Fundamentals",
          topics: [
            "How ad auctions work across platforms",
            "Key metrics: CPM, CPC, CTR, CPA, ROAS, frequency",
            "Campaign structure: campaign, ad set/group, ad level",
            "Funnel-based campaign objectives (awareness, consideration, conversion)",
            "Budgeting models: daily vs lifetime, CBO vs ABO",
            "Attribution windows and their impact on reporting",
          ],
        },
        {
          id: "5.2",
          title: "Meta Ads (Facebook & Instagram)",
          topics: [
            "Meta Ads Manager interface and campaign setup",
            "Meta Pixel and Conversions API installation",
            "Audience targeting: core, custom, and lookalike audiences",
            "Advantage+ campaigns and broad targeting strategies",
            "Ad formats: single image, carousel, video, collection",
            "Creative testing frameworks (hook, angle, format variations)",
            "Retargeting funnels and dynamic product ads",
            "Reading Meta Ads reporting and diagnosing underperformance",
          ],
        },
        {
          id: "5.3",
          title: "Google Ads",
          topics: [
            "Google Ads account structure: campaigns, ad groups, keywords",
            "Search campaigns: match types, negative keywords, quality score",
            "Google Display Network and remarketing campaigns",
            "Performance Max campaigns overview",
            "YouTube ads within Google Ads",
            "Writing high-CTR search ad copy with extensions",
            "Conversion tracking setup with Google Tag Manager",
          ],
        },
        {
          id: "5.4",
          title: "TikTok Ads & Emerging Platforms",
          topics: [
            "TikTok Ads Manager setup and campaign objectives",
            "Spark Ads and organic-style creative strategy",
            "TikTok audience targeting and Smart Targeting",
            "Creative best practices for native-feeling TikTok ads",
            "Overview of Pinterest and Snapchat ads for niche audiences",
          ],
        },
        {
          id: "5.5",
          title: "Creative Testing & Budget Optimization",
          topics: [
            "Building a creative testing matrix (hooks x formats x angles)",
            "Statistical significance basics for A/B testing ads",
            "Scaling winning ads: vertical vs horizontal scaling",
            "Budget allocation across funnel stages",
            "Calculating breakeven ROAS and target CPA",
            "Killing underperforming ads: decision frameworks",
          ],
        },
      ],
      exercises: [
        "Set up a full Meta Ads campaign structure in a test ad account",
        "Write 5 ad variations for an A/B creative test",
        "Build a Google Search campaign with keyword match types and negatives",
        "Calculate ROAS and CPA targets for a sample budget",
      ],
      assignments: [
        "Submit a complete paid media plan across Meta, Google, and TikTok for the capstone brand",
        "Produce a creative testing matrix with 6 ad variations and rationale",
      ],
      projects: [
        "Multi-Platform Paid Ads Campaign Plan with budgets, targeting, and creatives",
      ],
      outcomes: [
        "Can structure and launch campaigns on Meta, Google, and TikTok Ads",
        "Can build targeting strategies and lookalike audiences",
        "Can design and test ad creatives systematically",
        "Can manage budgets and optimize toward ROAS/CPA goals",
      ],
      assessment: "Paid media plan graded on targeting logic, budget allocation, and creative strategy rigor",
    },
    {
      number: 6,
      title: "Email Marketing, Funnels, Landing Pages & CRO",
      overview: "Design full-funnel email sequences, high-converting landing pages, and apply conversion rate optimization principles to maximize revenue from existing traffic.",
      objectives: [
        "Build automated email funnels for acquisition and retention",
        "Write high-converting email sequences and subject lines",
        "Design landing pages using conversion-focused structure",
        "Apply A/B testing and CRO methodology",
        "Set up marketing automation workflows",
      ],
      sections: [
        {
          id: "6.1",
          title: "Email Marketing Fundamentals",
          topics: [
            "Email marketing platforms overview (Mailchimp, Klaviyo, ConvertKit)",
            "List building strategies and lead magnets",
            "Email deliverability: SPF, DKIM, DMARC basics",
            "Segmentation strategies for personalized email",
            "Subject line and preview text optimization",
            "Email design best practices for mobile and desktop",
          ],
        },
        {
          id: "6.2",
          title: "Funnel Design & Automation",
          topics: [
            "Welcome sequences and onboarding flows",
            "Abandoned cart and browse abandonment flows",
            "Post-purchase and win-back sequences",
            "Nurture sequences for long sales cycles",
            "Building automation workflows with triggers and conditions",
            "Mapping funnels to the customer journey from Week 1",
          ],
        },
        {
          id: "6.3",
          title: "Landing Page Design",
          topics: [
            "Anatomy of a high-converting landing page",
            "Above-the-fold messaging and hero sections",
            "Social proof placement: testimonials, logos, reviews",
            "Building landing pages with tools like Unbounce, Framer, or Webflow",
            "Form design and reducing friction",
            "Mobile-first landing page principles",
          ],
        },
        {
          id: "6.4",
          title: "Conversion Rate Optimization (CRO)",
          topics: [
            "The CRO process: hypothesis, test, measure, iterate",
            "A/B testing tools and statistical significance",
            "Heatmaps and session recordings with Hotjar/Microsoft Clarity",
            "Identifying friction points in funnels",
            "Pricing page and checkout optimization",
            "Building a CRO backlog and prioritization framework (ICE/PIE)",
          ],
        },
        {
          id: "6.5",
          title: "Marketing Automation & CRM Basics",
          topics: [
            "Connecting email tools to CRMs (HubSpot basics)",
            "Lead scoring fundamentals",
            "Tagging and segmentation logic in automation platforms",
            "Reporting on funnel and email performance (open rate, CTR, revenue per email)",
          ],
        },
      ],
      exercises: [
        "Write a 5-email welcome sequence for a fictional brand",
        "Design a landing page wireframe with CRO principles applied",
        "Set up an abandoned cart flow in a chosen email platform",
        "Run a mock A/B test hypothesis using the ICE framework",
      ],
      assignments: [
        "Build and submit a complete email funnel (welcome + nurture + abandoned cart) for the capstone brand",
        "Design and submit a landing page mockup with a documented CRO rationale",
      ],
      projects: [
        "End-to-End Funnel: Landing Page + Email Automation Sequence",
      ],
      outcomes: [
        "Can design and build automated email funnels",
        "Can write high-converting email copy and subject lines",
        "Can design conversion-focused landing pages",
        "Understands and applies CRO testing methodology",
      ],
      assessment: "Funnel and landing page deliverables graded on conversion logic, copywriting, and design clarity",
    },
    {
      number: 7,
      title: "Influencer & Community Marketing, Analytics, Attribution & AI Tools",
      overview: "Learn to run influencer campaigns, build community-led growth, master analytics and attribution modeling, and integrate AI tools into marketing workflows.",
      objectives: [
        "Plan and execute an influencer marketing campaign",
        "Design a community-led growth strategy",
        "Build multi-channel analytics dashboards and attribution models",
        "Apply AI tools across research, content, and analysis workflows",
        "Interpret data to make strategic marketing decisions",
      ],
      sections: [
        {
          id: "7.1",
          title: "Influencer Marketing",
          topics: [
            "Types of influencers: nano, micro, macro, celebrity",
            "Influencer discovery and vetting tools",
            "Negotiating rates and contracts with creators",
            "Briefing influencers for authentic content",
            "UGC (user-generated content) licensing and whitelisting/Spark Ads",
            "Measuring influencer campaign ROI",
          ],
        },
        {
          id: "7.2",
          title: "Community Marketing & Growth",
          topics: [
            "Building brand communities on Discord, Slack, and Circle",
            "Community-led growth vs traditional acquisition",
            "Ambassador and referral program design",
            "Facilitating engagement and moderating communities",
            "Measuring community health metrics",
          ],
        },
        {
          id: "7.3",
          title: "Marketing Analytics & Dashboards",
          topics: [
            "Building cross-channel dashboards with Looker Studio",
            "Connecting GA4, ad platforms, and CRM data",
            "Defining and tracking North Star metrics",
            "Cohort analysis and retention curves",
            "Reporting cadences: weekly, monthly, quarterly reviews",
          ],
        },
        {
          id: "7.4",
          title: "Attribution Modeling",
          topics: [
            "First-touch vs last-touch vs multi-touch attribution",
            "Linear, time-decay, and position-based attribution models",
            "Challenges of attribution in a cookieless, privacy-first world",
            "Media mix modeling basics",
            "Using UTM parameters correctly across all campaigns",
          ],
        },
        {
          id: "7.5",
          title: "AI Tools for Marketers",
          topics: [
            "Using ChatGPT and Claude for content ideation and drafting",
            "AI image and video generation tools for creative production",
            "AI-assisted keyword research and SEO content briefs",
            "AI ad copy generation and creative variation tools",
            "AI-powered analytics summarization and insight generation",
            "Building custom GPTs/prompts for repeatable marketing workflows",
            "Ethical and quality-control considerations when using AI content",
          ],
        },
      ],
      exercises: [
        "Draft an influencer brief and outreach message for a micro-influencer campaign",
        "Build a Looker Studio dashboard pulling GA4 and ad platform data",
        "Compare attribution results using two different attribution models",
        "Use an AI tool to generate and refine a full content brief",
      ],
      assignments: [
        "Submit an influencer campaign plan with budget, briefs, and KPIs",
        "Submit a cross-channel analytics dashboard with attribution notes for the capstone brand",
      ],
      projects: [
        "Influencer Campaign Plan + Analytics Dashboard with Attribution Model",
      ],
      outcomes: [
        "Can plan and manage influencer and community marketing campaigns",
        "Can build cross-channel analytics dashboards",
        "Understands attribution models and their tradeoffs",
        "Can integrate AI tools into daily marketing workflows",
      ],
      assessment: "Dashboard and influencer plan graded on data accuracy, strategic insight, and AI-tool integration",
    },
    {
      number: 8,
      title: "Agency Business, Freelancing & Capstone Go-To-Market Campaign",
      overview: "Learn how to package and sell digital marketing services as a freelancer or agency, then plan, build, and present a complete go-to-market campaign as your capstone.",
      objectives: [
        "Understand the business models of freelancing vs running an agency",
        "Package services, price offers, and pitch clients",
        "Build a personal brand and portfolio to win clients",
        "Synthesize all prior weeks into one full go-to-market campaign",
        "Present a complete, data-backed marketing strategy to stakeholders",
      ],
      sections: [
        {
          id: "8.1",
          title: "Freelancing as a Digital Marketer",
          topics: [
            "Choosing a niche and service offer",
            "Building a portfolio with no prior clients",
            "Pricing models: hourly, project-based, retainer, performance-based",
            "Finding clients: cold outreach, referrals, freelance platforms, content marketing",
            "Writing proposals and contracts",
            "Managing client communication and expectations",
          ],
        },
        {
          id: "8.2",
          title: "Building & Running an Agency",
          topics: [
            "Agency business models: full-service vs specialized",
            "Team structure and hiring for an early-stage agency",
            "Productizing services into packages",
            "Client onboarding and reporting systems",
            "Scaling operations with tools and SOPs",
            "Common agency pitfalls and how to avoid them",
          ],
        },
        {
          id: "8.3",
          title: "Personal Branding & Sales",
          topics: [
            "Building an authority-driven personal brand on LinkedIn/X",
            "Creating case studies that sell your work",
            "Sales call structure for service-based marketing offers",
            "Handling objections and pricing conversations",
            "Building a lead-generation system for your own services",
          ],
        },
        {
          id: "8.4",
          title: "Capstone Strategy Development",
          topics: [
            "Synthesizing positioning, ICP, and journey mapping into one strategy",
            "Selecting the optimal channel mix for the chosen business",
            "Building the full campaign brief: goals, KPIs, budget, timeline",
            "Integrating content, social, SEO, paid, email, and CRO components",
            "Building the measurement and reporting plan",
          ],
        },
        {
          id: "8.5",
          title: "Capstone Build & Presentation",
          topics: [
            "Assembling all campaign assets into one deliverable",
            "Building a stakeholder-ready presentation deck",
            "Rehearsing and delivering a campaign pitch",
            "Incorporating feedback and revising the strategy",
            "Publishing the capstone as a portfolio case study",
          ],
        },
      ],
      exercises: [
        "Draft a freelance service package with 3 pricing tiers",
        "Write a cold outreach message and a client proposal template",
        "Build a one-page capstone campaign brief",
        "Practice pitching the capstone campaign to a peer for feedback",
      ],
      assignments: [
        "Submit a freelance/agency positioning and pricing package for your own services",
        "Submit the full capstone go-to-market campaign document and presentation deck",
      ],
      projects: [
        "Capstone: Full Go-To-Market Campaign combining positioning, content, social, SEO, paid ads, email, and analytics",
      ],
      outcomes: [
        "Can package, price, and pitch digital marketing services",
        "Understands agency and freelance business models",
        "Can synthesize the full marketing stack into one coherent strategy",
        "Can confidently present a complete marketing campaign to stakeholders",
      ],
      assessment: "Capstone go-to-market campaign graded on strategic coherence, execution detail, and presentation quality",
    },
  ],
};
