// Frontend Development — Professional Diploma Curriculum
import frontendImg from "@/assets/curriculum/frontend.jpg";
import type { CourseCurriculum } from "./types";

// ---------- FRONTEND DEVELOPMENT (Master Template) ----------
export const frontendDevelopment: CourseCurriculum = {
  slug: "frontend-development",
  title: "Frontend Development",
  tagline: "Professional Diploma",
  duration: "3 Months (12 Weeks)",
  months: 3,
  totalWeeks: 12,
  level: "Beginner → Intermediate → Advanced → Industry Ready",
  projectsCount: "15+",
  capstone: "1 Enterprise-Level Project",
  goal: "Train students to become professional Frontend Engineers capable of working in startups, agencies, and enterprise teams.",
  overview:
    "A cohort-based, project-driven journey through the modern frontend stack. Students go from writing their first HTML tag to shipping a production React + TypeScript application with authentication, state management, testing, and deployment.",
  image: frontendImg,
  weeks: [
    {
      number: 1,
      title: "Professional Developer Environment",
      overview:
        "Week 1 establishes the mental model of the web and equips every student with a professional, reproducible development workstation and AI-augmented workflow before a single production line of code is written.",
      objectives: [
        "Understand how the modern web works end-to-end, from DNS resolution to pixel rendering",
        "Set up a professional developer workstation with terminal, editor, and Node tooling",
        "Use AI coding assistants productively and responsibly inside a real workflow",
        "Navigate the command line and file system with confidence",
        "Understand the client-server model and how browsers negotiate connections",
      ],
      sections: [
        {
          id: "1.1",
          title: "Introduction to Software Development",
          topics: [
            "What is Software Engineering?",
            "Frontend vs Backend vs Fullstack roles",
            "Web Architecture (client, server, database)",
            "Client-Server Communication model",
            "Request Lifecycle (DNS → TCP → TLS → HTTP → render)",
            "Browser Rendering Pipeline (parse, style, layout, paint, composite)",
            "Static vs Dynamic Websites",
            "SPA vs MPA architectural tradeoffs",
            "Jamstack architecture",
            "CSR vs SSR vs SSG vs ISR",
            "How job roles map to the stack (Junior/Mid/Senior Frontend)",
          ],
        },
        {
          id: "1.2",
          title: "Development Environment",
          topics: [
            "VS Code Mastery (workspace, settings.json, multi-cursor)",
            "VS Code Shortcuts for speed editing",
            "Essential Extensions (ESLint, Prettier, GitLens, Error Lens)",
            "Chrome DevTools (Elements, Console, Network, Sources, Lighthouse)",
            "Node.js runtime and version management (nvm/fnm)",
            "npm package manager basics",
            "pnpm workspaces and performance benefits",
            "yarn as an alternative package manager",
            "Terminal Commands (cd, ls, mkdir, rm, mv, cp, grep, pipes)",
            "Environment Variables and .env files",
            "Configuring a personal dotfiles setup",
          ],
        },
        {
          id: "1.3",
          title: "Internet Fundamentals",
          topics: [
            "DNS resolution and record types (A, CNAME, MX)",
            "HTTP methods and status codes",
            "HTTPS and TLS handshake basics",
            "IP Address and ports",
            "Browser Cache (memory cache, disk cache, cache headers)",
            "Cookies (attributes, SameSite, Secure, HttpOnly)",
            "Sessions vs tokens",
            "Local Storage API",
            "Session Storage API",
            "CORS (preflight requests, headers, common errors)",
            "CDN and edge delivery",
          ],
        },
        {
          id: "1.4",
          title: "Productivity & AI-Assisted Development",
          topics: [
            "AI Coding Assistants overview",
            "ChatGPT for debugging and explanation",
            "GitHub Copilot inline suggestions and chat",
            "Cursor as an AI-native editor",
            "Claude for large-context code review",
            "Gemini for multimodal coding tasks",
            "Prompt Engineering for Developers (context, constraints, iteration)",
            "Verifying AI output and avoiding hallucinated APIs",
            "Building a personal productivity system (Notion/Obsidian for dev notes)",
          ],
        },
        {
          id: "1.5",
          title: "Professional Habits",
          topics: [
            "Reading documentation effectively (MDN, official docs)",
            "Writing a clear bug report",
            "Time-boxing and the Pomodoro technique for coding",
            "Setting up a daily learning log",
            "Joining developer communities (Discord, Stack Overflow, X)",
          ],
        },
      ],
      exercises: [
        "Configure VS Code with 10 essential extensions and a custom settings.json",
        "Trace a full HTTP request in Chrome DevTools Network tab and annotate each phase",
        "Write 20 terminal commands to navigate and manage files",
        "Install and switch Node versions with nvm across two projects",
        "Diagram the browser rendering pipeline from memory",
      ],
      assignments: [
        "Document your development workflow in a README with screenshots",
        "Compare 3 AI coding assistants and write a short review with pros/cons",
        "Write a one-page explainer of CSR vs SSR vs SSG with real-world examples",
      ],
      projects: ["Personal Dev Environment Setup Guide (Markdown)"],
      outcomes: [
        "Fully configured professional dev environment",
        "Confident with terminal, Git basics, and browser tooling",
        "Clear mental model of how the web works end-to-end",
        "Able to use AI tools as a productivity multiplier, not a crutch",
      ],
      assessment: "Live setup walkthrough + short quiz on web fundamentals",
    },
    {
      number: 2,
      title: "HTML5 (Professional)",
      overview:
        "A deep dive into writing semantic, accessible, and SEO-ready markup that forms a solid structural foundation for every subsequent styling and scripting layer.",
      objectives: [
        "Write semantic, accessible, SEO-friendly HTML",
        "Build production-quality forms and multimedia experiences",
        "Diagnose and fix accessibility issues using automated and manual audits",
        "Structure documents for both machines (SEO/crawlers) and humans (screen readers)",
      ],
      sections: [
        { id: "2.1", title: "HTML Foundations", topics: ["HTML Syntax and document structure", "Elements vs tags", "Attributes (global and element-specific)", "Comments", "DOCTYPE and quirks mode", "Void elements", "Nesting rules", "Whitespace handling", "Character encoding (charset, entities)"] },
        { id: "2.2", title: "Semantic HTML", topics: ["header", "footer", "nav", "main", "section", "article", "aside", "figure/figcaption", "picture", "details/summary", "time", "address", "mark", "when to use div vs semantic tags"] },
        { id: "2.3", title: "Forms", topics: ["Advanced form structure (fieldset, legend, label)", "Client-side Validation", "Pattern attribute and regex", "Accessible form labelling", "Input Types (email, tel, date, range, color, file)", "Form APIs (Constraint Validation API)", "autocomplete and autofocus", "Multi-step form UX"] },
        { id: "2.4", title: "Multimedia", topics: ["Video element and controls", "Audio element", "SVG inline vs external", "Canvas basics", "Responsive embeds (iframe)", "Accessible captions and transcripts"] },
        { id: "2.5", title: "SEO HTML", topics: ["Meta Tags (title, description, viewport)", "Open Graph tags", "Twitter Cards", "Structured Data (JSON-LD)", "Schema.org vocabularies", "Canonical URLs", "Sitemap and robots.txt basics"] },
        { id: "2.6", title: "Accessibility", topics: ["ARIA roles and attributes", "Screen Readers (VoiceOver/NVDA basics)", "Semantic Accessibility (landmark regions)", "Keyboard Navigation and focus order", "Skip links", "Color contrast requirements", "Accessible naming (aria-label, aria-labelledby)"] },
        { id: "2.7", title: "Performance", topics: ["Lazy Loading images/iframes", "Responsive Images", "srcset and sizes attributes", "picture element art direction", "Preload/prefetch hints", "Reducing DOM size for faster paint"] },
      ],
      exercises: [
        "Rewrite a div-heavy page using semantic elements",
        "Build 5 form types with native validation and no JavaScript",
        "Add Open Graph + Schema.org metadata to a page",
        "Add ARIA landmarks and test with a screen reader",
        "Convert a fixed-size image gallery to a responsive srcset gallery",
      ],
      assignments: [
        "Run a Lighthouse accessibility audit and fix all issues",
        "Write a JSON-LD structured data block for a product page",
      ],
      projects: ["Build a complete business website using semantic HTML only"],
      outcomes: [
        "Master of semantic, accessible, SEO-ready HTML5",
        "Able to build fully accessible forms without a framework",
        "Comfortable auditing and fixing accessibility violations",
      ],
      assessment: "Peer accessibility review + Lighthouse score ≥ 95",
    },
    {
      number: 3,
      title: "CSS3 (Complete Professional)",
      overview:
        "The complete modern CSS toolkit — from the cascade and box model to Grid, Flexbox, animation, and CSS architecture used in production design systems.",
      objectives: [
        "Build responsive, animated, production-grade interfaces with modern CSS",
        "Master layout systems (Flexbox and Grid) for any UI pattern",
        "Apply a scalable CSS architecture across a multi-page project",
        "Optimize CSS for performance and maintainability",
      ],
      sections: [
        { id: "3.1", title: "CSS Fundamentals", topics: ["Selectors (combinators, pseudo-classes, pseudo-elements)", "Specificity calculation", "Cascade and layers (@layer)", "Inheritance", "Box model (content-box vs border-box)", "Units (px, em, rem, vh, vw, %)"] },
        { id: "3.2", title: "Layout", topics: ["Display types (block, inline, inline-block)", "Position (static, relative, absolute, fixed, sticky)", "Float and clearfix (legacy)", "Flexbox (main/cross axis, grow/shrink/basis)", "Grid (template areas, auto-fit/auto-fill, fr unit)", "Multi-column layout"] },
        { id: "3.3", title: "Typography", topics: ["Font Loading strategies (font-display)", "Variable Fonts", "Responsive Typography with clamp()", "Line-height and vertical rhythm", "Web-safe fonts vs custom fonts"] },
        { id: "3.4", title: "Responsive Design", topics: ["Mobile First methodology", "Breakpoints strategy", "Media Queries (min-width, prefers-color-scheme)", "Container Queries", "Fluid layouts vs fixed breakpoints"] },
        { id: "3.5", title: "Advanced CSS", topics: ["Custom Properties (CSS Variables)", "calc()", "clamp()", "min()", "max()", "CSS functions (var, attr)"] },
        { id: "3.6", title: "Animation", topics: ["Transition properties and easing", "Keyframes", "Timing Functions (cubic-bezier)", "Transform (translate, scale, rotate)", "3D Effects (perspective, transform-style)", "will-change for performance"] },
        { id: "3.7", title: "Modern CSS", topics: ["Native Nesting", "Logical Properties (inline/block)", "Aspect Ratio", "Object Fit / Object Position", "Backdrop Filter", "Mask and clip-path", ":has() selector"] },
        { id: "3.8", title: "CSS Architecture", topics: ["BEM naming convention", "Utility CSS philosophy", "Component-scoped CSS", "CSS Modules basics", "Design tokens"] },
        { id: "3.9", title: "CSS Optimization", topics: ["Critical CSS extraction", "Performance profiling with DevTools", "Render Blocking CSS", "Minimizing reflow/repaint", "PurgeCSS concepts"] },
      ],
      exercises: [
        "Recreate 5 hero sections from top SaaS sites",
        "Build a responsive grid gallery with hover animation",
        "Implement a sticky navbar with scroll-triggered style changes",
        "Build a pricing table using CSS Grid with equal-height cards",
      ],
      assignments: ["Publish a CSS pattern library with 15 reusable components"],
      projects: ["Clone Apple Homepage"],
      outcomes: [
        "Ability to translate any Figma design to pixel-perfect responsive CSS",
        "Confident with both Flexbox and Grid for any layout",
        "Can architect scalable CSS for a multi-page site",
      ],
      assessment: "Design-to-code challenge under time constraints",
    },
    {
      number: 4,
      title: "Git & GitHub",
      overview:
        "Professional version control workflows used in real engineering teams, from local branching to collaborative pull requests and open-source contribution.",
      objectives: [
        "Collaborate professionally with Git, branches, and pull requests",
        "Resolve merge conflicts confidently",
        "Understand and apply common Git workflows used in teams",
        "Contribute to an external open-source codebase",
      ],
      sections: [
        { id: "4.1", title: "Git Core", topics: ["Git Installation and config (user.name/email)", "Repository initialization", "Branches and branch naming conventions", "Merge strategies (fast-forward, three-way)", "Rebase vs merge", "Cherry Pick", "Stash and stash pop", "Git log and reflog", "Undoing changes (revert, reset, checkout)"] },
        { id: "4.2", title: "GitHub Workflow", topics: ["Pull Requests and code review etiquette", "Git Flow branching model", "Trunk-based development", "Collaboration via Issues and Projects", "Open Source Contribution etiquette", "Conflict Resolution strategies", "Protected branches and required reviews", "GitHub Actions basics for CI"] },
      ],
      exercises: [
        "Simulate a merge conflict and resolve it",
        "Open a PR to an open-source project",
        "Practice interactive rebase to clean up commit history",
        "Recover a lost commit using reflog",
      ],
      assignments: ["Contribute one accepted PR to a public repository"],
      projects: ["Collaborative Team Project (3 devs, 1 repo)"],
      outcomes: [
        "Comfortable with branching strategies and code reviews",
        "Able to resolve merge conflicts without fear",
        "Understands team Git workflows used in industry",
      ],
      assessment: "PR review checklist scored by an instructor",
    },
    {
      number: 5,
      title: "Tailwind CSS",
      overview:
        "Utility-first CSS at production speed — building consistent, themeable design systems without leaving your markup.",
      objectives: [
        "Build fast, consistent UIs with a utility-first CSS framework",
        "Configure and extend Tailwind's design tokens for a brand",
        "Compose reusable component patterns without custom CSS files",
        "Optimize Tailwind output for production",
      ],
      sections: [
        { id: "5.1", title: "Core Concepts", topics: ["Installation (CLI, Vite plugin)", "Configuration file structure", "Theme Customization (colors, spacing, fonts)", "Responsive Utilities (sm, md, lg, xl, 2xl)", "State variants (hover, focus, active, dark)"] },
        { id: "5.2", title: "Layout", topics: ["Flex utilities", "Grid utilities", "Container and max-width", "Gap utilities", "Positioning utilities"] },
        { id: "5.3", title: "Styling", topics: ["Typography utilities", "Color palette usage", "Spacing scale", "Shadows", "Borders and rings", "Opacity and blend modes"] },
        { id: "5.4", title: "Components", topics: ["Buttons with variants", "Cards", "Tables", "Forms", "Navigation bars", "Modals and dialogs"] },
        { id: "5.5", title: "Customization", topics: ["Tailwind Config extension", "Custom Utilities with @layer", "Plugins ecosystem", "Using CSS variables inside Tailwind theme"] },
        { id: "5.6", title: "Optimization", topics: ["Purging unused classes (content config)", "Tree Shaking in build", "Performance measurement", "Using class-variance-authority for variants", "clsx/tailwind-merge patterns"] },
      ],
      exercises: [
        "Convert a plain-CSS project to Tailwind",
        "Design a reusable button system with variants using cva",
        "Build a dark mode toggle using Tailwind's dark variant",
        "Build a responsive navbar with a mobile hamburger menu",
      ],
      assignments: ["Build a design system with 20 components in Tailwind"],
      projects: ["Modern SaaS Landing Page"],
      outcomes: [
        "Ship polished UIs 3× faster using Tailwind",
        "Comfortable extending Tailwind's theme for any brand",
        "Can build a component variant system without writing custom CSS",
      ],
      assessment: "Timed UI build challenge scored on fidelity and speed",
    },
    {
      number: 6,
      title: "JavaScript (Complete)",
      overview: "The largest module in the course. Deep, from-first-principles JavaScript covering language internals, asynchronous programming, the DOM, and browser APIs.",
      objectives: [
        "Master modern JavaScript from language internals to browser APIs",
        "Understand execution context, closures, and the event loop deeply",
        "Write clean asynchronous code using promises and async/await",
        "Manipulate the DOM and consume browser APIs confidently",
      ],
      sections: [
        { id: "6.1", title: "Fundamentals", topics: ["Variables (var/let/const)", "Scope (block, function, global)", "Hoisting", "Closures", "Functions (declarations, expressions, arrow)", "Objects and property descriptors", "Arrays and array methods", "Loops (for, for...of, for...in, while)", "Conditions and truthy/falsy values", "Type coercion"] },
        { id: "6.2", title: "ES6+", topics: ["Modules (import/export)", "Arrow Functions and lexical this", "Destructuring (object/array)", "Spread operator", "Rest parameters", "Template Literals and tagged templates", "Optional chaining and nullish coalescing", "Symbols and iterators"] },
        { id: "6.3", title: "Advanced JavaScript", topics: ["Execution Context", "Call Stack", "Event Loop (microtasks vs macrotasks)", "Memory Management", "Garbage Collection", "Prototype chain", "Prototypal Inheritance", "this Keyword resolution rules", "bind, call, apply", "Currying and partial application"] },
        { id: "6.4", title: "Asynchronous JavaScript", topics: ["Callback pattern and callback hell", "Promise (states, chaining, Promise.all/race/allSettled)", "Async Await syntax and error handling", "Fetch API", "Axios library", "AbortController for cancellation", "Debounce and throttle patterns"] },
        { id: "6.5", title: "DOM", topics: ["Traversing the DOM tree", "DOM Manipulation (createElement, appendChild)", "Event Delegation", "Mutation Observer", "Event bubbling vs capturing", "Custom events"] },
        { id: "6.6", title: "Browser APIs", topics: ["Local Storage API", "Session Storage API", "Geolocation API", "Clipboard API", "Notifications API", "Intersection Observer API", "Resize Observer API", "Web Workers (introduction)"] },
        { id: "6.7", title: "Error Handling", topics: ["try/catch/finally", "throw and custom Error classes", "Debugging with breakpoints", "Reading a stack trace", "Defensive programming patterns"] },
        { id: "6.8", title: "Design Patterns", topics: ["Module Pattern", "Factory Pattern", "Singleton", "Observer pattern", "Pub/Sub pattern"] },
      ],
      exercises: [
        "30 daily JS katas",
        "Rebuild Array.prototype.map/filter/reduce from scratch",
        "Implement a debounce and throttle function from scratch",
        "Build a Promise polyfill",
        "Trace and diagram the event loop for a mixed sync/async script",
      ],
      assignments: ["Explain the event loop with your own diagram + example"],
      projects: ["Calculator", "Weather App", "Movie App", "Quiz App", "Expense Tracker"],
      outcomes: [
        "Deep, professional-level command of modern JavaScript",
        "Able to reason about async execution order confidently",
        "Comfortable working directly with the DOM and browser APIs",
      ],
      assessment: "Live coding interview covering closures, async, and the DOM",
    },
    {
      number: 7,
      title: "TypeScript",
      overview:
        "Adding static types to JavaScript to catch bugs earlier, document intent, and scale codebases safely across teams.",
      objectives: [
        "Write safer, more maintainable JavaScript with types",
        "Model complex domain data with interfaces, generics, and unions",
        "Configure a strict TypeScript project from scratch",
        "Migrate an existing JavaScript codebase to TypeScript",
      ],
      sections: [
        { id: "7.1", title: "Type System", topics: ["Type System basics (primitives, arrays, tuples)", "Interfaces vs type aliases", "Union and intersection Types", "Generics", "Utility Types (Partial, Pick, Omit, Record)", "Type Narrowing with typeof/instanceof"] },
        { id: "7.2", title: "Enums, Modules & Declarations", topics: ["Enums vs const objects", "Modules and namespace resolution", "Declaration Files (.d.ts)", "Type Inference rules", "Strict Mode flags (strictNullChecks, noImplicitAny)", "tsconfig.json deep dive"] },
        { id: "7.3", title: "Advanced Types", topics: ["Advanced Types (mapped types, conditional types)", "Type Guards and discriminated unions", "Template literal types", "Generic constraints (extends keyof)", "Type-safe API client patterns"] },
      ],
      exercises: [
        "Type 20 real-world function signatures",
        "Fix a broken generic API client",
        "Write a discriminated union to model API loading/success/error states",
        "Create 5 custom utility types from scratch",
      ],
      assignments: ["Publish a fully-typed utility npm package"],
      projects: ["Convert a JavaScript project into TypeScript"],
      outcomes: [
        "Confident authoring strict, well-typed TypeScript codebases",
        "Able to model complex domain logic with the type system",
        "Comfortable reading and writing declaration files",
      ],
      assessment: "Code review of a fully migrated TypeScript project",
    },
    {
      number: 8,
      title: "React.js (Professional)",
      overview:
        "The core production framework module — building full-featured React applications with routing, forms, authentication, state management, testing, and deployment.",
      objectives: [
        "Ship production React applications with routing, state, auth, and testing",
        "Design reusable, composable component architectures",
        "Integrate real REST APIs with authentication and pagination",
        "Test and deploy a React application with confidence",
      ],
      sections: [
        { id: "8.1", title: "React Core", topics: ["JSX syntax and rules", "Components (function components)", "Props and prop drilling", "State with useState", "Component Lifecycle via useEffect", "Hooks rules", "Event Handling in React", "Conditional rendering", "Lists and keys"] },
        { id: "8.2", title: "Advanced React", topics: ["Custom Hooks", "Compound Components pattern", "Context API", "Performance Optimization (useMemo, useCallback)", "Memoization with React.memo", "Code Splitting", "Lazy Loading with React.lazy/Suspense", "useReducer for complex state"] },
        { id: "8.3", title: "Routing", topics: ["React Router setup", "Nested Routes", "Protected Routes", "Dynamic Routes and params", "Route loaders and data fetching", "404/error routes"] },
        { id: "8.4", title: "Forms", topics: ["React Hook Form setup", "Schema Validation with Zod", "Controlled vs uncontrolled Components", "Field arrays and dynamic forms", "Form error UX"] },
        { id: "8.5", title: "State Management", topics: ["Context API for global state", "Redux Toolkit (slices, thunks)", "Zustand (Introduction)", "Server State vs Client State", "TanStack Query for server state"] },
        { id: "8.6", title: "API Integration", topics: ["Axios instance configuration", "REST API consumption patterns", "Authentication headers", "Pagination strategies", "Infinite Scroll", "Optimistic Updates", "Handling loading/error states"] },
        { id: "8.7", title: "Authentication", topics: ["JWT structure and storage strategies", "Refresh Tokens flow", "Protected Pages/route guards", "Role-Based Access Control (Frontend)", "Persisting auth state"] },
        { id: "8.8", title: "Advanced Topics", topics: ["Error Boundaries", "Suspense for data fetching", "Portals", "Higher-Order Components", "Render Props pattern", "Composition Patterns over inheritance"] },
        { id: "8.9", title: "Testing", topics: ["Unit Testing with Vitest/Jest", "React Testing Library queries", "Component Testing best practices", "Mocking API calls in tests", "Snapshot testing tradeoffs"] },
        { id: "8.10", title: "Deployment", topics: ["Vercel deployment workflow", "Netlify deployment workflow", "Environment Variables in production", "Build Optimization (bundle analysis)", "CI checks before deploy"] },
      ],
      exercises: [
        "Rewrite 3 vanilla JS apps as React apps",
        "Build 5 custom hooks (useDebounce, useFetch, useLocalStorage, etc.)",
        "Build a protected route wrapper with role checks",
        "Write RTL tests for a form component",
      ],
      assignments: ["Implement JWT auth flow with refresh tokens"],
      projects: ["Enterprise Admin Dashboard"],
      outcomes: [
        "Ready to work on production React codebases in any team",
        "Comfortable choosing the right state management tool for a problem",
        "Able to test and deploy a React app end-to-end",
      ],
      assessment: "React coding challenge + component design review",
    },
    {
      number: 9,
      title: "Professional Engineering Practices",
      overview:
        "Shifting from writing code that works to writing code that scales — clean architecture, reusable systems, and rigorous audits used in senior engineering roles.",
      objectives: [
        "Work like a senior engineer: clean code, architecture, audits",
        "Apply SOLID-inspired principles to frontend component design",
        "Structure a scalable component and folder architecture",
        "Run and act on accessibility, performance, and security audits",
      ],
      sections: [
        { id: "9.1", title: "Code Quality", topics: ["Clean Code principles", "SOLID Principles (Frontend Perspective)", "Folder Structures (feature-based vs type-based)", "Naming conventions", "Code review checklists", "ESLint/Prettier enforcement"] },
        { id: "9.2", title: "Architecture", topics: ["Component Architecture layering", "Reusable UI Systems", "Atomic Design (atoms, molecules, organisms)", "Design tokens and theming architecture", "Monorepo basics for shared UI"] },
        { id: "9.3", title: "Audits", topics: ["Accessibility Audits (axe, WAVE)", "Lighthouse Audits (performance, SEO, best practices)", "Performance Optimization (bundle size, Core Web Vitals)", "Security Best Practices (XSS, CSP, dependency audits)", "SEO for React Applications (meta management, SSR considerations)"] },
        { id: "9.4", title: "Documentation & Collaboration", topics: ["Writing architecture decision records (ADRs)", "Storybook for component documentation", "Onboarding docs for new engineers", "Cross-functional collaboration with design/PM"] },
      ],
      exercises: [
        "Refactor a messy component into an atomic design system",
        "Run and fix a full Lighthouse audit",
        "Write an ADR for a state management decision",
        "Set up Storybook for 5 shared components",
      ],
      assignments: ["Write an architecture doc for your capstone"],
      projects: ["Design system + audit report for a real product"],
      outcomes: [
        "Think and communicate like a senior frontend engineer",
        "Able to structure large codebases for maintainability",
        "Comfortable running and interpreting technical audits",
      ],
      assessment: "Architecture review presentation to peers",
    },
    {
      number: 10,
      title: "Career Accelerator",
      overview:
        "Turning technical skill into a job offer — portfolio, personal brand, interview preparation, and freelance income channels.",
      objectives: [
        "Land your first (or next) frontend role",
        "Build a portfolio that demonstrates real engineering judgment",
        "Prepare for technical and behavioral interviews",
        "Establish freelance or contract income channels",
      ],
      sections: [
        { id: "10.1", title: "Portfolio", topics: ["GitHub Portfolio curation", "Technical Resume writing", "LinkedIn Optimization", "Writing compelling case studies", "Pinning and presenting top repos"] },
        { id: "10.2", title: "Work Channels", topics: ["Freelancing (Upwork, Fiverr, Contra)", "Cold outreach to startups", "Building a referral network", "Pricing your first freelance projects"] },
        { id: "10.3", title: "Interviews", topics: ["Technical Interviews structure", "Whiteboard & Live Coding Preparation", "System design basics for frontend", "Behavioral interview frameworks (STAR)", "Salary negotiation basics"] },
        { id: "10.4", title: "Brand", topics: ["Personal Branding strategy", "Building a Developer Portfolio site", "AI-Assisted Development Workflows for productivity", "Writing technical blog posts", "Building in public on X/LinkedIn"] },
      ],
      exercises: [
        "Mock interview with feedback",
        "Rewrite your LinkedIn headline & about section",
        "Do 10 live-coding practice problems under time pressure",
        "Draft 3 outreach messages for freelance leads",
      ],
      assignments: ["Publish a portfolio site + 5 case studies"],
      projects: ["Personal Portfolio Website"],
      outcomes: [
        "Interview-ready resume, LinkedIn, and portfolio",
        "Comfortable navigating technical and behavioral interviews",
        "Has an active freelance or job-search pipeline",
      ],
      assessment: "Mock interview scored by an instructor panel",
    },
    {
      number: 11,
      title: "E-commerce App with API",
      overview:
        "A full production-shaped e-commerce build integrating real APIs, cart persistence, checkout, and authenticated account areas — the flagship pre-capstone project.",
      objectives: [
        "Ship a real, deployed e-commerce experience",
        "Integrate a real payment provider in test mode",
        "Manage complex global state across cart, auth, and orders",
        "Handle real-world edge cases (out of stock, failed payment, empty states)",
      ],
      sections: [
        { id: "11.1", title: "Product & Cart", topics: ["Product listing with filtering and sorting", "Product detail pages", "Filters and search", "Cart state management", "Persistent cart (localStorage/backend sync)", "Quantity and stock validation"] },
        { id: "11.2", title: "Checkout", topics: ["Address form with validation", "Payment integration (Stripe test mode)", "Order confirmation and receipts", "Coupon/discount logic", "Shipping calculation basics"] },
        { id: "11.3", title: "Auth & Account", topics: ["Sign up / sign in flows", "Order history page", "Protected account routes", "Wishlist/favorites feature", "Profile editing"] },
        { id: "11.4", title: "Polish & Edge Cases", topics: ["Empty and error states", "Loading skeletons", "Toast notifications", "Responsive checkout UX", "Analytics events on key actions"] },
      ],
      exercises: [
        "Wire cart to global state with optimistic updates",
        "Build a coupon code validation flow",
        "Add skeleton loaders for product listing",
      ],
      assignments: ["Integrate a real payment provider in test mode"],
      projects: ["Deployed E-commerce App with API"],
      outcomes: [
        "Portfolio-grade e-commerce project",
        "Real experience with payment integration",
        "Confident handling complex, multi-page application state",
      ],
      assessment: "Full walkthrough demo covering cart, checkout, and account flows",
    },
    {
      number: 12,
      title: "Enterprise-Level Capstone Project",
      overview:
        "The final, portfolio-defining project: a fully planned, built, tested, and deployed enterprise-grade application presented to a panel of hiring partners.",
      objectives: [
        "Deliver a production-ready, deployed capstone",
        "Practice full-cycle product planning from spec to deployment",
        "Present technical decisions clearly to a non-technical and technical audience",
        "Ship with proper CI/CD, monitoring, and documentation",
      ],
      sections: [
        { id: "12.1", title: "Planning", topics: ["Writing a product spec", "System architecture diagram", "Component tree planning", "API contract design", "Choosing the tech stack and justifying tradeoffs"] },
        { id: "12.2", title: "Build", topics: ["React + TypeScript + Tailwind implementation", "Integrating real APIs", "Authentication and authorization", "State management at scale", "Responsive design across breakpoints", "Accessibility pass"] },
        { id: "12.3", title: "Ship", topics: ["CI/CD pipeline setup", "Deployment to production", "Analytics integration", "Error tracking (Sentry)", "Writing full technical documentation", "Post-launch monitoring plan"] },
        { id: "12.4", title: "Presentation", topics: ["Structuring a demo day pitch", "Live-demoing under pressure", "Answering technical Q&A", "Presenting metrics and impact"] },
      ],
      exercises: ["Weekly demo + peer code review"],
      assignments: ["Write full technical documentation and README"],
      projects: ["Enterprise Capstone (deployed) with polished GitHub repo"],
      outcomes: [
        "A portfolio-defining, production-ready project",
        "Full-cycle experience from spec to shipped, monitored product",
        "Confidence presenting technical work to hiring panels",
      ],
      assessment: "Panel demo day with hiring partners",
    },
  ],
};
