import frontendImg from "@/assets/curriculum/frontend.jpg";
import type { CourseCurriculum } from "./types";


// ---------- FRONTEND DEVELOPMENT (Master Template) ----------
export const frontendDevelopment: CourseCurriculum = {
  slug: "frontend-development",
  title: "Frontend Development",
  tagline: "Professional Diploma",
  duration: "3 Months (12 Weeks)",
  months: 3,
  totalWeeks: 12,
  level: "Beginner → Intermediate → Advanced → Industry Ready",
  projectsCount: "15+",
  capstone: "1 Enterprise-Level Project",
  goal: "Train students to become professional Frontend Engineers capable of working in startups, agencies, and enterprise teams.",
  overview:
    "A cohort-based, project-driven journey through the modern frontend stack. Students go from writing their first HTML tag to shipping a production React + TypeScript application with authentication, state management, testing, and deployment.",
  image: frontendImg,
  weeks: [
    {
      number: 1,
      title: "Professional Developer Environment",
      objectives: [
        "Understand how the modern web works end-to-end",
        "Set up a professional developer workstation",
        "Use AI coding assistants productively",
      ],
      sections: [
        {
          id: "1.1",
          title: "Introduction to Software Development",
          topics: [
            "What is Software Engineering?",
            "Frontend vs Backend vs Fullstack",
            "Web Architecture",
            "Client-Server Communication",
            "Request Lifecycle",
            "Browser Rendering Pipeline",
            "Static vs Dynamic Websites",
            "SPA vs MPA",
            "Jamstack",
            "CSR vs SSR vs SSG",
          ],
        },
        {
          id: "1.2",
          title: "Development Environment",
          topics: [
            "VS Code Mastery",
            "VS Code Shortcuts",
            "Essential Extensions",
            "Chrome DevTools",
            "Node.js",
            "npm",
            "pnpm",
            "yarn",
            "Terminal Commands",
            "Environment Variables",
          ],
        },
        {
          id: "1.3",
          title: "Internet Fundamentals",
          topics: [
            "DNS", "HTTP", "HTTPS", "IP Address", "Browser Cache",
            "Cookies", "Sessions", "Local Storage", "Session Storage",
            "CORS", "CDN",
          ],
        },
        {
          id: "1.4",
          title: "Productivity",
          topics: [
            "AI Coding Assistants",
            "ChatGPT", "GitHub Copilot", "Cursor", "Claude", "Gemini",
            "Prompt Engineering for Developers",
          ],
        },
      ],
      exercises: [
        "Configure VS Code with 10 essential extensions",
        "Trace a full HTTP request in Chrome DevTools Network tab",
        "Write 20 terminal commands to navigate and manage files",
      ],
      assignments: [
        "Document your development workflow in a README",
        "Compare 3 AI coding assistants and write a short review",
      ],
      projects: ["Personal Dev Environment Setup Guide (Markdown)"],
      outcomes: [
        "Fully configured professional dev environment",
        "Confident with terminal, Git basics, and browser tooling",
      ],
      assessment: "Live setup walkthrough + short quiz on web fundamentals",
    },
    {
      number: 2,
      title: "HTML5 (Professional)",
      objectives: [
        "Write semantic, accessible, SEO-friendly HTML",
        "Build production-quality forms and multimedia experiences",
      ],
      sections: [
        { id: "2.1", title: "HTML Foundations", topics: ["HTML Syntax", "Elements", "Attributes", "Comments", "DOCTYPE"] },
        { id: "2.2", title: "Semantic HTML", topics: ["header", "footer", "nav", "main", "section", "article", "aside", "figure", "picture", "details", "summary"] },
        { id: "2.3", title: "Forms", topics: ["Advanced Forms", "Validation", "Pattern", "Accessibility", "Input Types", "Form APIs"] },
        { id: "2.4", title: "Multimedia", topics: ["Video", "Audio", "SVG", "Canvas"] },
        { id: "2.5", title: "SEO HTML", topics: ["Meta Tags", "Open Graph", "Twitter Cards", "Structured Data", "Schema"] },
        { id: "2.6", title: "Accessibility", topics: ["ARIA", "Screen Readers", "Semantic Accessibility", "Keyboard Navigation"] },
        { id: "2.7", title: "Performance", topics: ["Lazy Loading", "Responsive Images", "srcset", "picture element"] },
      ],
      exercises: [
        "Rewrite a div-heavy page using semantic elements",
        "Build 5 form types with native validation",
        "Add Open Graph + Schema.org metadata to a page",
      ],
      assignments: ["Run a Lighthouse accessibility audit and fix all issues"],
      projects: ["Build a complete business website using semantic HTML only"],
      outcomes: ["Master of semantic, accessible, SEO-ready HTML5"],
      assessment: "Peer accessibility review + Lighthouse score ≥ 95",
    },
    {
      number: 3,
      title: "CSS3 (Complete Professional)",
      objectives: ["Build responsive, animated, production-grade interfaces with modern CSS"],
      sections: [
        { id: "3.1", title: "CSS Fundamentals", topics: ["Selectors", "Specificity", "Cascade", "Inheritance"] },
        { id: "3.2", title: "Layout", topics: ["Display", "Position", "Float", "Flexbox", "Grid"] },
        { id: "3.3", title: "Typography", topics: ["Font Loading", "Variable Fonts", "Responsive Typography"] },
        { id: "3.4", title: "Responsive Design", topics: ["Mobile First", "Breakpoints", "Media Queries", "Container Queries"] },
        { id: "3.5", title: "Advanced CSS", topics: ["Variables", "calc()", "clamp()", "min()", "max()"] },
        { id: "3.6", title: "Animation", topics: ["Transition", "Keyframes", "Timing Functions", "Transform", "3D Effects"] },
        { id: "3.7", title: "Modern CSS", topics: ["Nesting", "Logical Properties", "Aspect Ratio", "Object Fit", "Backdrop Filter", "Mask"] },
        { id: "3.8", title: "CSS Architecture", topics: ["BEM", "Utility CSS", "Component CSS"] },
        { id: "3.9", title: "CSS Optimization", topics: ["Critical CSS", "Performance", "Render Blocking"] },
      ],
      exercises: ["Recreate 5 hero sections from top SaaS sites", "Build a responsive grid gallery with animation"],
      assignments: ["Publish a CSS pattern library with 15 reusable components"],
      projects: ["Clone Apple Homepage"],
      outcomes: ["Ability to translate any Figma design to pixel-perfect responsive CSS"],
      assessment: "Design-to-code challenge under time constraints",
    },
    {
      number: 4,
      title: "Git & GitHub",
      objectives: ["Collaborate professionally with Git, branches, and pull requests"],
      sections: [
        { id: "4.1", title: "Git Core", topics: ["Git Installation", "Repository", "Branches", "Merge", "Rebase", "Cherry Pick", "Stash"] },
        { id: "4.2", title: "GitHub Workflow", topics: ["Pull Requests", "Git Flow", "GitHub Workflow", "Collaboration", "Open Source Contribution", "Conflict Resolution"] },
      ],
      exercises: ["Simulate a merge conflict and resolve it", "Open a PR to an open-source project"],
      assignments: ["Contribute one accepted PR to a public repository"],
      projects: ["Collaborative Team Project (3 devs, 1 repo)"],
      outcomes: ["Comfortable with branching strategies and code reviews"],
      assessment: "PR review checklist scored by an instructor",
    },
    {
      number: 5,
      title: "Tailwind CSS",
      objectives: ["Build fast, consistent UIs with a utility-first CSS framework"],
      sections: [
        { id: "5.1", title: "Core Concepts", topics: ["Installation", "Configuration", "Theme Customization", "Responsive Utilities"] },
        { id: "5.2", title: "Layout", topics: ["Flex", "Grid", "Container"] },
        { id: "5.3", title: "Styling", topics: ["Typography", "Colors", "Spacing", "Shadows", "Borders"] },
        { id: "5.4", title: "Components", topics: ["Buttons", "Cards", "Tables", "Forms", "Navigation"] },
        { id: "5.5", title: "Customization", topics: ["Tailwind Config", "Custom Utilities", "Plugins"] },
        { id: "5.6", title: "Optimization", topics: ["Purging", "Tree Shaking", "Performance"] },
      ],
      exercises: ["Convert a plain-CSS project to Tailwind", "Design a reusable button system with variants"],
      assignments: ["Build a design system with 20 components in Tailwind"],
      projects: ["Modern SaaS Landing Page"],
      outcomes: ["Ship polished UIs 3× faster using Tailwind"],
    },
    {
      number: 6,
      title: "JavaScript (Complete)",
      overview: "The largest module in the course. Deep, from-first-principles JavaScript.",
      objectives: ["Master modern JavaScript from language internals to browser APIs"],
      sections: [
        { id: "6.1", title: "Fundamentals", topics: ["Variables", "Scope", "Hoisting", "Closures", "Functions", "Objects", "Arrays", "Loops", "Conditions"] },
        { id: "6.2", title: "ES6+", topics: ["Modules", "Arrow Functions", "Destructuring", "Spread", "Rest", "Template Literals"] },
        { id: "6.3", title: "Advanced JavaScript", topics: ["Execution Context", "Call Stack", "Event Loop", "Memory Management", "Garbage Collection", "Prototype", "Prototypal Inheritance", "this Keyword", "bind", "call", "apply"] },
        { id: "6.4", title: "Asynchronous JavaScript", topics: ["Callback", "Promise", "Async Await", "Fetch", "Axios", "AbortController"] },
        { id: "6.5", title: "DOM", topics: ["Traversing", "Manipulation", "Event Delegation", "Mutation Observer"] },
        { id: "6.6", title: "Browser APIs", topics: ["Local Storage", "Session Storage", "Geolocation", "Clipboard", "Notifications", "Intersection Observer", "Resize Observer"] },
        { id: "6.7", title: "Error Handling", topics: ["try catch", "throw", "debugging", "stack trace"] },
        { id: "6.8", title: "Design Patterns", topics: ["Module Pattern", "Factory Pattern", "Singleton", "Observer"] },
      ],
      exercises: ["30 daily JS katas", "Rebuild Array.prototype.map/filter/reduce from scratch"],
      assignments: ["Explain the event loop with your own diagram + example"],
      projects: ["Calculator", "Weather App", "Movie App", "Quiz App", "Expense Tracker"],
      outcomes: ["Deep, professional-level command of modern JavaScript"],
      assessment: "Live coding interview covering closures, async, and the DOM",
    },
    {
      number: 7,
      title: "TypeScript",
      objectives: ["Write safer, more maintainable JavaScript with types"],
      sections: [
        { id: "7.1", title: "Type System", topics: ["Type System", "Interfaces", "Types", "Generics", "Utility Types", "Type Narrowing"] },
        { id: "7.2", title: "Enums, Modules & Declarations", topics: ["Enums", "Modules", "Declaration Files", "Type Inference", "Strict Mode"] },
        { id: "7.3", title: "Advanced Types", topics: ["Advanced Types", "Type Guards"] },
      ],
      exercises: ["Type 20 real-world function signatures", "Fix a broken generic API client"],
      assignments: ["Publish a fully-typed utility npm package"],
      projects: ["Convert a JavaScript project into TypeScript"],
      outcomes: ["Confident authoring strict, well-typed TypeScript codebases"],
    },
    {
      number: 8,
      title: "React.js (Professional)",
      objectives: ["Ship production React applications with routing, state, auth, and testing"],
      sections: [
        { id: "8.1", title: "React Core", topics: ["JSX", "Components", "Props", "State", "Lifecycle", "Hooks", "Event Handling"] },
        { id: "8.2", title: "Advanced React", topics: ["Custom Hooks", "Compound Components", "Context API", "Performance Optimization", "Memoization", "Code Splitting", "Lazy Loading"] },
        { id: "8.3", title: "Routing", topics: ["React Router", "Nested Routes", "Protected Routes", "Dynamic Routes"] },
        { id: "8.4", title: "Forms", topics: ["React Hook Form", "Validation", "Controlled Components"] },
        { id: "8.5", title: "State Management", topics: ["Context API", "Redux Toolkit", "Zustand (Introduction)", "Server State vs Client State"] },
        { id: "8.6", title: "API Integration", topics: ["Axios", "REST API", "Authentication", "Pagination", "Infinite Scroll", "Optimistic Updates"] },
        { id: "8.7", title: "Authentication", topics: ["JWT", "Refresh Tokens", "Protected Pages", "Role-Based Access Control (Frontend)"] },
        { id: "8.8", title: "Advanced Topics", topics: ["Error Boundaries", "Suspense", "Portals", "Higher-Order Components", "Render Props", "Composition Patterns"] },
        { id: "8.9", title: "Testing", topics: ["Unit Testing", "React Testing Library", "Component Testing"] },
        { id: "8.10", title: "Deployment", topics: ["Vercel", "Netlify", "Environment Variables", "Build Optimization"] },
      ],
      exercises: ["Rewrite 3 vanilla JS apps as React apps", "Build 5 custom hooks"],
      assignments: ["Implement JWT auth flow with refresh tokens"],
      projects: ["Enterprise Admin Dashboard"],
      outcomes: ["Ready to work on production React codebases in any team"],
      assessment: "React coding challenge + component design review",
    },
    {
      number: 9,
      title: "Professional Engineering Practices",
      objectives: ["Work like a senior engineer: clean code, architecture, audits"],
      sections: [
        { id: "9.1", title: "Code Quality", topics: ["Clean Code", "SOLID Principles (Frontend Perspective)", "Folder Structures"] },
        { id: "9.2", title: "Architecture", topics: ["Component Architecture", "Reusable UI Systems", "Atomic Design"] },
        { id: "9.3", title: "Audits", topics: ["Accessibility Audits", "Lighthouse Audits", "Performance Optimization", "Security Best Practices", "SEO for React Applications"] },
      ],
      exercises: ["Refactor a messy component into an atomic design system", "Run and fix a full Lighthouse audit"],
      assignments: ["Write an architecture doc for your capstone"],
      projects: ["Design system + audit report for a real product"],
      outcomes: ["Think and communicate like a senior frontend engineer"],
    },
    {
      number: 10,
      title: "Career Accelerator",
      objectives: ["Land your first (or next) frontend role"],
      sections: [
        { id: "10.1", title: "Portfolio", topics: ["GitHub Portfolio", "Technical Resume", "LinkedIn Optimization"] },
        { id: "10.2", title: "Work Channels", topics: ["Freelancing (Upwork, Fiverr, Contra)"] },
        { id: "10.3", title: "Interviews", topics: ["Technical Interviews", "Whiteboard & Live Coding Preparation"] },
        { id: "10.4", title: "Brand", topics: ["Personal Branding", "Building a Developer Portfolio", "AI-Assisted Development Workflows"] },
      ],
      exercises: ["Mock interview with feedback", "Rewrite your LinkedIn headline & about"],
      assignments: ["Publish a portfolio site + 5 case studies"],
      projects: ["Personal Portfolio Website"],
      outcomes: ["Interview-ready resume, LinkedIn, and portfolio"],
    },
    {
      number: 11,
      title: "E-commerce App with API",
      objectives: ["Ship a real, deployed e-commerce experience"],
      sections: [
        { id: "11.1", title: "Product & Cart", topics: ["Product listing", "Product detail", "Filters", "Cart state", "Persistent cart"] },
        { id: "11.2", title: "Checkout", topics: ["Address form", "Payment integration (test mode)", "Order confirmation"] },
        { id: "11.3", title: "Auth & Account", topics: ["Sign up / sign in", "Order history", "Protected account routes"] },
      ],
      exercises: ["Wire cart to global state with optimistic updates"],
      assignments: ["Integrate a real payment provider in test mode"],
      projects: ["Deployed E-commerce App with API"],
      outcomes: ["Portfolio-grade e-commerce project"],
    },
    {
      number: 12,
      title: "Enterprise-Level Capstone Project",
      objectives: ["Deliver a production-ready, deployed capstone"],
      sections: [
        { id: "12.1", title: "Planning", topics: ["Product spec", "System diagram", "Component tree"] },
        { id: "12.2", title: "Build", topics: ["React + TypeScript + Tailwind", "Real APIs", "Auth", "State management", "Responsive design"] },
        { id: "12.3", title: "Ship", topics: ["CI/CD", "Deployment", "Analytics", "Error tracking", "Documentation"] },
      ],
      exercises: ["Weekly demo + peer code review"],
      assignments: ["Write full technical documentation and README"],
      projects: ["Enterprise Capstone (deployed) with polished GitHub repo"],
      outcomes: ["A portfolio-defining, production-ready project"],
      assessment: "Panel demo day with hiring partners",
    },
  ],
};
