import type { CourseCurriculum } from "./types";
import img from "@/assets/curriculum/graphics.jpg";

export const graphicsDesign: CourseCurriculum = {
  slug: "graphics-design",
  title: "Graphics Design",
  tagline: "Professional Certificate",
  duration: "2 Months (8 Weeks)",
  months: 2,
  totalWeeks: 8,
  level: "Beginner to Job Ready",
  projectsCount: "10+",
  capstone: "1 Full Brand Identity System",
  goal: "Train complete beginners to become job-ready graphics designers capable of producing professional logos, brand identities, social media assets, print materials, and freelancing confidently with a strong portfolio.",
  overview: "An intensive 8-week hands-on program covering design fundamentals, colour theory, typography, and composition through to mastery of Photoshop, Illustrator, Canva, and Figma for graphics. Learners progress through logo design, brand identity systems, social media and print design, photo manipulation, motion graphics basics, and AI-assisted design tools, culminating in a full client-ready brand identity capstone and a polished portfolio for freelancing or employment.",
  image: img,
  weeks: [
    {
      number: 1,
      title: "Design Foundations: Principles, Colour Theory & Typography",
      overview: "Build the visual literacy and theoretical foundation every designer needs before touching software seriously.",
      objectives: [
        "Understand and apply the core principles of design",
        "Master colour theory and build effective palettes",
        "Understand typography classification, pairing, and hierarchy",
        "Develop an eye for visual balance and composition",
        "Set up a professional design workspace and toolkit",
      ],
      sections: [
        {
          id: "1.1",
          title: "Introduction to Graphic Design as a Career",
          topics: [
            "What graphic design is and where it is used",
            "Career paths: brand designer, social media designer, print designer, motion designer",
            "In-house vs agency vs freelance work",
            "Overview of the design industry in 2026",
            "Tools landscape: Adobe Creative Cloud, Canva, Figma",
            "How designers get paid: salary vs freelance vs passive income",
            "Building a growth mindset and critique culture",
            "Setting personal learning goals for the 8 weeks",
          ],
        },
        {
          id: "1.2",
          title: "Core Principles of Design",
          topics: [
            "Balance: symmetrical, asymmetrical, radial",
            "Contrast and emphasis",
            "Alignment and grid thinking",
            "Repetition and consistency",
            "Proximity and grouping",
            "White space (negative space) usage",
            "Visual hierarchy and focal points",
            "Rhythm and movement in a layout",
            "Unity and gestalt principles (proximity, similarity, closure)",
          ],
        },
        {
          id: "1.3",
          title: "Colour Theory",
          topics: [
            "The colour wheel: primary, secondary, tertiary colours",
            "Hue, saturation, brightness (HSB) explained",
            "Colour harmonies: complementary, analogous, triadic, split-complementary",
            "Warm vs cool colours and psychological effects",
            "Colour psychology across cultures and industries",
            "RGB vs CMYK vs HEX vs Pantone",
            "Building accessible colour palettes (contrast ratios)",
            "Tools: Coolors, Adobe Color, Colorhunt",
            "Applying colour theory to a mock brand",
          ],
        },
        {
          id: "1.4",
          title: "Typography Fundamentals",
          topics: [
            "Anatomy of a typeface (x-height, ascender, descender, kerning, leading)",
            "Type classifications: serif, sans-serif, script, display, monospace",
            "Choosing readable body fonts vs expressive display fonts",
            "Font pairing rules and common combinations",
            "Type hierarchy: headline, subhead, body, caption",
            "Tracking, kerning, and line-height best practices",
            "Free and licensed font resources (Google Fonts, Adobe Fonts)",
            "Common typography mistakes beginners make",
          ],
        },
        {
          id: "1.5",
          title: "Composition & Layout Thinking",
          topics: [
            "Rule of thirds and the golden ratio",
            "Grid systems: column grids, modular grids, baseline grids",
            "Visual weight and balance in a composition",
            "Framing and cropping for impact",
            "Creating focal points with size, colour, and contrast",
            "Layout for different formats: square, portrait, landscape",
            "Analysing professional designs for composition choices",
          ],
        },
      ],
      exercises: [
        "Recreate the colour wheel digitally and label harmonies",
        "Identify and annotate design principles in 10 real-world ads",
        "Pair 5 different font combinations for a mock brand",
        "Redesign a poorly composed flyer using grid principles",
        "Build a mood board expressing a chosen brand personality",
      ],
      assignments: [
        "Submit a personal colour palette (5 palettes, 5 colours each) with psychology notes",
        "Create a one-page typography style sheet showing hierarchy for a fictional brand",
      ],
      projects: [
        "Design a design-principles cheat sheet poster applying balance, contrast, hierarchy, and white space",
      ],
      outcomes: [
        "Can explain and apply the 8 core design principles confidently",
        "Can build harmonious, accessible colour palettes",
        "Can pair typefaces correctly for hierarchy and readability",
        "Understands composition and grid-based layout thinking",
      ],
      assessment: "Design principles quiz plus submission of colour palette and typography style sheet, graded on theory accuracy and application.",
    },
    {
      number: 2,
      title: "Mastering Canva & Figma for Graphics",
      overview: "Get productive fast with modern, accessible design tools before moving into the Adobe suite.",
      objectives: [
        "Navigate Canva confidently for social and print design",
        "Use Figma for graphic layout, components, and collaboration",
        "Build reusable templates and brand kits",
        "Understand file export settings for web and print",
        "Create first real client-style deliverables",
      ],
      sections: [
        {
          id: "2.1",
          title: "Canva Deep Dive",
          topics: [
            "Canva interface: workspace, elements, uploads, templates",
            "Working with the grid, guides, and alignment tools",
            "Text effects, curved text, and font pairing in Canva",
            "Using Canva Brand Kit: logos, colours, fonts",
            "Magic Resize for multi-format campaigns",
            "Background remover and photo effects",
            "Canva Pro features: Magic Studio, AI tools, animation",
            "Exporting for print (PDF print, bleed) vs web (PNG/JPG)",
            "Templates marketplace and customisation ethics",
          ],
        },
        {
          id: "2.2",
          title: "Figma for Graphic Designers",
          topics: [
            "Figma interface: frames, layers, pages, assets panel",
            "Vector basics in Figma: pen tool, boolean operations",
            "Auto layout for scalable graphic components",
            "Components, variants, and reusable design elements",
            "Working with grids, constraints, and alignment",
            "Plugins for designers: Unsplash, Iconify, Content Reel",
            "Exporting assets at multiple resolutions (1x, 2x, 3x)",
            "Collaboration: comments, sharing, version history",
          ],
        },
        {
          id: "2.3",
          title: "Building Templates & Brand Kits",
          topics: [
            "Structuring a reusable social media template set",
            "Creating a presentation/deck template",
            "Setting up shared colour and text styles",
            "Naming conventions and file organisation",
            "Creating a simple one-page brand style guide",
            "Version control for design files",
          ],
        },
        {
          id: "2.4",
          title: "File Formats & Export Settings",
          topics: [
            "Raster vs vector explained (JPG, PNG, SVG, PDF, AI)",
            "Resolution and DPI: 72 vs 150 vs 300",
            "Transparent backgrounds and PNG use cases",
            "Print-ready PDF export settings",
            "Colour profile considerations (RGB for screen, CMYK for print)",
            "Compressing files for web without losing quality",
          ],
        },
      ],
      exercises: [
        "Rebuild a random social media post found online using Canva",
        "Create a 5-slide pitch deck template in Figma with auto layout",
        "Build a reusable Instagram post + story template pair",
        "Export the same design correctly for web and for print",
      ],
      assignments: [
        "Design a 3-piece social media template kit (post, story, carousel) in Canva",
        "Recreate the same template kit in Figma using components and auto layout",
      ],
      projects: [
        "Produce a mini brand style sheet (colours, fonts, logo placeholder, 3 templates) for a fictional coffee brand",
      ],
      outcomes: [
        "Confidently builds graphics in both Canva and Figma",
        "Understands correct export settings for web vs print",
        "Can construct reusable, scalable design templates",
        "Has produced first client-style deliverable set",
      ],
      assessment: "Practical review of submitted template kits in Canva and Figma, graded on consistency, reusability, and export correctness.",
    },
    {
      number: 3,
      title: "Adobe Photoshop Mastery",
      overview: "Deep dive into raster editing, photo manipulation, and compositing using industry-standard Photoshop.",
      objectives: [
        "Master the Photoshop interface, layers, and selection tools",
        "Perform professional photo retouching and colour correction",
        "Use masks, blending modes, and adjustment layers non-destructively",
        "Create composite images through photo manipulation",
        "Prepare Photoshop files for web and print output",
      ],
      sections: [
        {
          id: "3.1",
          title: "Photoshop Interface & Core Tools",
          topics: [
            "Workspace setup, panels, and customisation",
            "Layers, layer groups, and layer styles",
            "Selection tools: marquee, lasso, quick selection, object selection AI",
            "Move, transform, free transform, and warp",
            "Brush tool settings and custom brushes",
            "Text tool and character/paragraph panels",
            "History panel and non-destructive workflow habits",
            "Smart objects and why they matter",
          ],
        },
        {
          id: "3.2",
          title: "Masking & Blending",
          topics: [
            "Layer masks vs clipping masks",
            "Selecting hair and complex edges (Select and Mask workspace)",
            "Blending modes explained (Multiply, Screen, Overlay, etc.)",
            "Adjustment layers: curves, levels, hue/saturation, colour balance",
            "Non-destructive dodge and burn technique",
            "Frequency separation basics for skin retouching",
            "Gradient maps for colour grading",
          ],
        },
        {
          id: "3.3",
          title: "Photo Retouching & Colour Correction",
          topics: [
            "Removing blemishes with spot healing and clone stamp",
            "Skin smoothing while retaining texture",
            "Correcting exposure, white balance, and contrast",
            "Colour grading a photo for mood",
            "Sharpening techniques (high pass, smart sharpen)",
            "Batch processing with actions",
          ],
        },
        {
          id: "3.4",
          title: "Photo Manipulation & Compositing",
          topics: [
            "Combining multiple images into one scene",
            "Matching lighting, shadows, and perspective",
            "Using generative fill and AI tools in Photoshop",
            "Creating realistic shadows and reflections",
            "Colour matching across composited elements",
            "Building a surreal/conceptual composite artwork",
          ],
        },
        {
          id: "3.5",
          title: "Exporting & Optimising for Web/Print",
          topics: [
            "Save for Web (legacy) vs Export As",
            "Image resolution and resizing without quality loss",
            "File format selection for different use cases",
            "Flattening vs preserving layers for future edits",
            "Setting up print bleed and CMYK conversion in Photoshop",
          ],
        },
      ],
      exercises: [
        "Retouch a portrait photo: skin, eyes, colour correction",
        "Remove a background using Select and Mask on complex hair",
        "Create a double-exposure effect using blending modes",
        "Colour grade three photos for three different moods",
        "Build a simple composite combining two stock photos",
      ],
      assignments: [
        "Full portrait retouch before/after submission with process notes",
        "Create an original surreal photo manipulation artwork (minimum 3 source images)",
      ],
      projects: [
        "Produce a magazine-style advertisement using photo manipulation and typography",
      ],
      outcomes: [
        "Confidently retouches and colour-corrects photographs",
        "Understands and applies non-destructive masking workflows",
        "Can composite multiple images into a believable scene",
        "Exports correctly optimised files for web and print",
      ],
      assessment: "Portfolio review of retouching and composite assignments, graded on technical execution and creative believability.",
    },
    {
      number: 4,
      title: "Adobe Illustrator & Logo Design",
      overview: "Master vector illustration and the complete professional logo design process from brief to final files.",
      objectives: [
        "Master vector drawing tools and the pen tool in Illustrator",
        "Understand the full logo design process end to end",
        "Design logos across multiple styles (wordmark, lettermark, icon, combination)",
        "Prepare final logo files for client delivery",
        "Critique and iterate designs based on feedback",
      ],
      sections: [
        {
          id: "4.1",
          title: "Illustrator Fundamentals",
          topics: [
            "Interface overview: artboards, layers, tool panel",
            "Pen tool mastery: anchor points, curves, handles",
            "Shape tools and shape builder for icon creation",
            "Pathfinder operations: unite, subtract, intersect, exclude",
            "Working with strokes, fills, and gradients",
            "Type tool and outlining text to paths",
            "Image trace for converting raster to vector",
            "Artboards for multi-size deliverables",
          ],
        },
        {
          id: "4.2",
          title: "The Logo Design Process",
          topics: [
            "Client briefing and discovery questionnaire",
            "Competitor and market research",
            "Sketching thumbnails by hand before digitising",
            "Types of logos: wordmark, lettermark, pictorial, abstract, mascot, combination, emblem",
            "Concept development: 3-5 distinct directions",
            "Refining shapes, proportions, and negative space tricks",
            "Choosing typography and colour for the mark",
            "Testing logo at small sizes and in black & white",
          ],
        },
        {
          id: "4.3",
          title: "Vector Icon & Illustration Design",
          topics: [
            "Grid-based icon design principles",
            "Creating a consistent icon set (stroke weight, corner radius)",
            "Flat illustration style basics",
            "Isometric illustration fundamentals",
            "Building a custom illustration for a brand",
          ],
        },
        {
          id: "4.4",
          title: "Logo Presentation & Delivery",
          topics: [
            "Creating mockup presentations for client pitching",
            "Logo usage guidelines: clear space, minimum size",
            "Colour variations: full colour, black, white, greyscale",
            "File deliverables: AI, EPS, SVG, PNG, PDF",
            "Common client feedback scenarios and how to respond professionally",
            "Contracts and revision limits for logo projects",
          ],
        },
      ],
      exercises: [
        "Trace a raster logo into clean vector paths",
        "Design 5 icon concepts on a fixed grid with consistent style",
        "Sketch 10 thumbnail logo concepts for a fictional client brief",
        "Build a logo clear-space and minimum-size guideline sheet",
      ],
      assignments: [
        "Complete a full logo design process for a fictional client: brief, research, sketches, 3 digital concepts, final refined logo",
        "Prepare a full logo delivery package (colour variations, file formats, usage guide)",
      ],
      projects: [
        "Design a complete logo suite (primary logo, submark, favicon-style icon) for a fictional startup",
      ],
      outcomes: [
        "Can execute the full professional logo design process independently",
        "Comfortable with vector tools and the Illustrator pen tool",
        "Produces client-ready logo delivery packages",
        "Can defend and present design decisions to a client",
      ],
      assessment: "Logo design process submission graded on research depth, concept variety, technical vector execution, and delivery package completeness.",
    },
    {
      number: 5,
      title: "Brand Identity Systems",
      overview: "Expand a single logo into a full, cohesive brand identity system ready for real-world application.",
      objectives: [
        "Understand what makes a complete brand identity system",
        "Build a full brand style guide from scratch",
        "Design consistent brand collateral across touchpoints",
        "Apply brand voice and visual tone across formats",
        "Prepare a professional brand guidelines document",
      ],
      sections: [
        {
          id: "5.1",
          title: "Brand Strategy Basics for Designers",
          topics: [
            "Brand vs logo vs identity: key distinctions",
            "Defining brand mission, vision, and values",
            "Target audience research and personas",
            "Brand personality archetypes (12 archetypes)",
            "Brand voice and tone guidelines",
            "Competitive positioning and differentiation",
          ],
        },
        {
          id: "5.2",
          title: "Building the Visual Identity System",
          topics: [
            "Primary and secondary colour palette definition",
            "Typography system: primary, secondary, and accent fonts",
            "Logo variations and lockups (horizontal, stacked, icon-only)",
            "Photography and imagery style direction",
            "Iconography and illustration style rules",
            "Patterns and textures as brand assets",
            "Grid systems for consistent layouts",
          ],
        },
        {
          id: "5.3",
          title: "Applying the Brand Across Collateral",
          topics: [
            "Business cards and stationery design",
            "Letterhead and email signature design",
            "Social media profile and cover branding",
            "Packaging mockups applying brand elements",
            "Signage and merchandise mockups",
            "Presentation deck templates on-brand",
          ],
        },
        {
          id: "5.4",
          title: "Brand Guidelines Document",
          topics: [
            "Structuring a professional brand book (10-25 pages)",
            "Do's and don'ts section for logo usage",
            "Colour codes: HEX, RGB, CMYK, Pantone reference",
            "Typography specimen pages",
            "Imagery and tone examples",
            "Exporting and presenting the guideline PDF to a client",
          ],
        },
      ],
      exercises: [
        "Define a brand personality and voice for a fictional client using an archetype",
        "Design 3 brand collateral mockups (business card, social cover, letterhead)",
        "Create a colour and typography specimen page",
      ],
      assignments: [
        "Develop a full brand strategy brief for a fictional business (mission, audience, personality, voice)",
        "Design a 10+ page brand guidelines document applying the strategy",
      ],
      projects: [
        "Build a mid-size brand identity system: logo suite, colour and type system, 4 collateral applications, and guideline document",
      ],
      outcomes: [
        "Understands brand strategy fundamentals relevant to designers",
        "Can build a complete, consistent visual identity system",
        "Produces professional brand guideline documents",
        "Applies brand identity correctly across varied collateral",
      ],
      assessment: "Brand system project graded on strategic clarity, visual consistency across applications, and guideline document professionalism.",
    },
    {
      number: 6,
      title: "Social Media & Print Design",
      overview: "Apply design skills to two of the most in-demand commercial categories: social media content and print production.",
      objectives: [
        "Design scroll-stopping social media graphics across platforms",
        "Understand print production requirements: CMYK, bleed, DPI",
        "Design flyers, banners, and packaging mockups",
        "Adapt a single campaign across multiple formats",
        "Prepare files correctly for professional print vendors",
      ],
      sections: [
        {
          id: "6.1",
          title: "Social Media Design Systems",
          topics: [
            "Platform-specific size guides: Instagram, Facebook, LinkedIn, TikTok, X",
            "Designing carousels that tell a visual story",
            "Content pillars and a monthly content calendar grid",
            "Designing scroll-stopping thumbnails and covers",
            "Animated post basics (Canva/simple motion) for engagement",
            "Analysing high-performing social ads for design cues",
          ],
        },
        {
          id: "6.2",
          title: "Print Production Fundamentals",
          topics: [
            "Understanding bleed, trim, and safe zones",
            "CMYK colour conversion and colour shift awareness",
            "DPI/resolution requirements for print (300 DPI standard)",
            "Paper stock and finish considerations (matte, gloss, uncoated)",
            "Preparing print-ready PDFs (marks, bleeds, colour profile)",
            "Common print production mistakes and how to avoid them",
          ],
        },
        {
          id: "6.3",
          title: "Flyer, Banner & Poster Design",
          topics: [
            "Structuring an effective flyer layout (hierarchy, CTA)",
            "Designing roll-up and pull-up banner layouts",
            "Large-format billboard/poster design considerations",
            "Event flyer design for nightlife, corporate, and community events",
            "Designing a multi-page brochure layout",
          ],
        },
        {
          id: "6.4",
          title: "Packaging Design Basics",
          topics: [
            "Packaging dies and dielines explained",
            "Designing a product label (box or pouch)",
            "Wrapping brand identity around 3D packaging mockups",
            "Using free packaging mockup templates for presentation",
            "Regulatory/label information considerations (basic awareness)",
          ],
        },
      ],
      exercises: [
        "Design a 5-slide Instagram carousel promoting a product",
        "Create a print-ready A5 flyer with correct bleed and CMYK setup",
        "Design a roll-up banner for a fictional conference",
        "Mock up a product label on a 3D packaging template",
      ],
      assignments: [
        "Design a full social media content calendar (10 posts) for a fictional brand launch",
        "Produce a print-ready flyer and banner pair using the same fictional brand identity from week 5",
      ],
      projects: [
        "Design a complete packaging concept (label design + 3D mockup presentation) for a fictional product",
      ],
      outcomes: [
        "Designs consistent, platform-optimised social media content",
        "Understands and applies correct print production standards",
        "Can design flyers, banners, and posters that convert",
        "Produces presentable packaging design mockups",
      ],
      assessment: "Combined social media calendar and print-ready file review, graded on design quality, platform accuracy, and print production correctness.",
    },
    {
      number: 7,
      title: "Motion Graphics Basics & AI Design Tools",
      overview: "Add motion and AI-powered workflows to the design toolkit to stay competitive in the modern design market.",
      objectives: [
        "Understand motion graphics principles and basic After Effects workflow",
        "Create simple animated graphics for social media",
        "Use AI image generation tools effectively and ethically in design work",
        "Integrate AI tools into a real design workflow to speed up production",
        "Evaluate quality and originality of AI-assisted output",
      ],
      sections: [
        {
          id: "7.1",
          title: "Motion Graphics Principles",
          topics: [
            "12 principles of animation applied to graphic motion",
            "Easing and timing curves for natural movement",
            "Keyframes and the animation timeline concept",
            "Designing with motion in mind from the static file",
            "Common animated formats: GIF, MP4, Lottie",
          ],
        },
        {
          id: "7.2",
          title: "After Effects & Canva Animation Basics",
          topics: [
            "After Effects interface: composition, timeline, layers",
            "Animating position, scale, rotation, and opacity",
            "Simple text animation techniques (kinetic typography)",
            "Importing Illustrator/Photoshop layers into After Effects",
            "Exporting for social media (Media Encoder basics)",
            "Canva's built-in animation and video tools for quick outputs",
          ],
        },
        {
          id: "7.3",
          title: "AI Tools for Designers",
          topics: [
            "Overview of AI image generators: Midjourney, DALL-E, Adobe Firefly, Ideogram",
            "Prompt engineering for consistent, on-brand visual style",
            "Using generative fill and generative expand in Photoshop",
            "AI background removal and upscaling tools",
            "AI for mockup generation and rapid concepting",
            "AI copywriting tools for design captions and briefs",
          ],
        },
        {
          id: "7.4",
          title: "Ethics, Licensing & Workflow Integration",
          topics: [
            "Copyright and ownership considerations with AI-generated content",
            "Client disclosure and transparency around AI usage",
            "Stock licensing basics (royalty-free vs rights-managed)",
            "Building an efficient hybrid AI + manual design workflow",
            "Avoiding generic or plagiarised AI output",
          ],
        },
      ],
      exercises: [
        "Animate a simple logo reveal in After Effects (5-10 seconds)",
        "Create a kinetic typography quote animation",
        "Generate and refine 5 AI concept images for a brand mood board using prompt iteration",
        "Use generative fill to extend a background in a real photo",
      ],
      assignments: [
        "Produce a 10-15 second animated social media promo combining static assets and motion",
        "Create an AI-assisted concept board for a fictional brand, documenting prompts and refinement process",
      ],
      projects: [
        "Design and animate a short branded intro/outro sting for a fictional company's video content",
      ],
      outcomes: [
        "Can create simple, effective animated graphics for social platforms",
        "Comfortable navigating After Effects for graphic motion",
        "Uses AI design tools productively and ethically",
        "Integrates AI into a real design workflow without sacrificing originality",
      ],
      assessment: "Review of animated promo and AI concept board, graded on motion quality, creative use of AI, and workflow documentation.",
    },
    {
      number: 8,
      title: "Freelancing, Client Work & Capstone Brand Identity",
      overview: "Transition from student to professional: pricing, client management, portfolio building, and a full capstone brand identity project.",
      objectives: [
        "Understand freelance pricing models and how to quote projects",
        "Manage client communication, briefs, and revisions professionally",
        "Build a standout design portfolio",
        "Plan and execute a full brand identity capstone independently",
        "Prepare for job or freelance market entry",
      ],
      sections: [
        {
          id: "8.1",
          title: "Freelancing & Pricing",
          topics: [
            "Freelance platforms overview: Upwork, Fiverr, Behance, local networks",
            "Pricing models: hourly, per-project, value-based pricing",
            "Writing proposals and pitching to clients",
            "Creating contracts and scopes of work",
            "Handling scope creep and revision limits",
            "Invoicing and getting paid internationally",
          ],
        },
        {
          id: "8.2",
          title: "Client Management & Communication",
          topics: [
            "Running an effective discovery/briefing call",
            "Writing clear creative briefs from vague client input",
            "Presenting concepts persuasively",
            "Handling difficult feedback and revision requests",
            "Building long-term client relationships and referrals",
            "Setting boundaries and professional email etiquette",
          ],
        },
        {
          id: "8.3",
          title: "Portfolio Building",
          topics: [
            "Choosing a portfolio platform: Behance, Dribbble, personal site",
            "Curating best work vs most work",
            "Writing effective case studies for each project",
            "Presenting process, not just final output",
            "Personal branding as a designer (logo, bio, tone)",
            "Optimising portfolio for recruiters and clients",
          ],
        },
        {
          id: "8.4",
          title: "Career Preparation",
          topics: [
            "Types of design roles: junior designer, brand designer, freelancer, in-house",
            "Building a resume/CV tailored for design roles",
            "Preparing for design interviews and portfolio walkthroughs",
            "Networking on LinkedIn and design communities",
            "Continuing education: staying current with design trends",
          ],
        },
        {
          id: "8.5",
          title: "Capstone Project: Full Brand Identity System",
          topics: [
            "Choosing a real or realistic capstone client concept",
            "Conducting discovery, research, and strategy",
            "Logo design process through to final refined mark",
            "Full visual identity system: colour, type, imagery, iconography",
            "Collateral application set: social, print, packaging, digital",
            "Comprehensive brand guidelines document",
            "Final presentation deck and client pitch simulation",
          ],
        },
      ],
      exercises: [
        "Draft a sample freelance proposal and quote for a mock client brief",
        "Write a case study for one existing project from the course",
        "Conduct a mock discovery call role-play and summarise the brief produced",
        "Peer-review a classmate's portfolio and give structured feedback",
      ],
      assignments: [
        "Build a live or PDF portfolio featuring at least 5 best projects from the course with case studies",
        "Prepare a freelance rate card and one-page service offering document",
      ],
      projects: [
        "Capstone: Design and deliver a complete brand identity system for a chosen client concept, including logo suite, full visual identity, at least 6 collateral applications, a full brand guidelines document, and a final client pitch presentation",
      ],
      outcomes: [
        "Understands how to price, pitch, and manage freelance design work",
        "Has a professional, case-study-driven portfolio ready to share",
        "Can independently execute a full brand identity project end to end",
        "Is prepared to enter the job market or freelance market confidently",
      ],
      assessment: "Final capstone brand identity system presented and defended in a mock client pitch, graded on strategy, design execution, consistency, and presentation professionalism.",
    },
  ],
};
